// packages/solid-intlayer/src/analytics/AnalyticsProvider.tsx
import type { Component, ParentProps } from 'solid-js';
import { useAnalytics } from './useAnalytics';

/**
 * Runs {@link useAnalytics} and renders its children unchanged. Mounted inside
 * {@link IntlayerProvider} alongside `EditorProvider`.
 */
export const AnalyticsProvider: Component<ParentProps> = ({ children }) => {
  useAnalytics();

  return children;
};

// packages/react-intlayer/src/analytics/AnalyticsProvider.tsx
import type { FC, PropsWithChildren } from 'react';
import { useAnalytics } from './useAnalytics';

/**
 * Runs {@link useAnalytics} and renders its children unchanged. Mounted inside
 * {@link IntlayerProvider} alongside `EditorProvider`.
 */
export const AnalyticsProvider: FC<PropsWithChildren> = ({ children }) => {
  useAnalytics();

  return children;
};
