// packages/react-intlayer/src/editor/ContentSelector.tsx
'use client';

import type { NodeProps } from '@intlayer/core/interpreter';
import { isEnabled } from '@intlayer/editor/isEnabled';
import { createElement, type FC, type HTMLAttributes } from 'react';

export type ContentSelectorProps = NodeProps &
  Omit<HTMLAttributes<HTMLDivElement>, 'children'>;

// ── Tree-shake constants ──────────────────────────────────────────────────────
// When these env vars are injected at build time, bundlers eliminate the
// branches guarded by these constants.

/**
 * True when the editor is explicitly disabled at build time.
 */
const TREE_SHAKE_EDITOR = process.env['INTLAYER_EDITOR_ENABLED'] === 'false';

export const ContentSelector: FC<ContentSelectorProps> = ({
  children,
  dictionaryKey,
  keyPath,
}) => {
  if (TREE_SHAKE_EDITOR || !isEnabled) {
    return children;
  }

  return createElement(
    'intlayer-content-selector-wrapper',
    {
      'key-path': JSON.stringify(keyPath),
      'dictionary-key': dictionaryKey,
    },
    children
  );
};

// packages/solid-intlayer/src/editor/ContentSelector.tsx
import type { NodeProps } from '@intlayer/core/interpreter';
import { isEnabled } from '@intlayer/editor/isEnabled';
import type { Component, JSX } from 'solid-js';
import { Dynamic } from 'solid-js/web';

// JSX declaration for the Lit web components
declare module 'solid-js' {
  namespace JSX {
    interface IntrinsicElements {
      'intlayer-content-selector-wrapper': JSX.HTMLAttributes<HTMLElement> & {
        'key-path'?: string;
        'dictionary-key'?: string;
      };
    }
  }
}

export type ContentSelectorWrapperProps = NodeProps &
  Omit<JSX.HTMLAttributes<HTMLDivElement>, 'children'> & {
    children?: JSX.Element;
  };

// ── Tree-shake constants ──────────────────────────────────────────────────────
// When these env vars are injected at build time, bundlers eliminate the
// branches guarded by these constants.

/**
 * True when the editor is explicitly disabled at build time.
 */
const TREE_SHAKE_EDITOR = process.env['INTLAYER_EDITOR_ENABLED'] === 'false';

export const ContentSelector: Component<ContentSelectorWrapperProps> = (
  props
) => {
  if (TREE_SHAKE_EDITOR || !isEnabled) {
    return props.children;
  }

  return (
    <Dynamic
      component="intlayer-content-selector-wrapper"
      attr:key-path={JSON.stringify(props.keyPath)}
      attr:dictionary-key={props.dictionaryKey}
    >
      {props.children}
    </Dynamic>
  );
};
