// packages/preact-intlayer/src/editor/ContentSelector.tsx
import type { NodeProps } from '@intlayer/core/interpreter';
import { isEnabled } from '@intlayer/editor/isEnabled';
import type { FunctionalComponent, HTMLAttributes } from 'preact';
import { useEffect } from 'preact/hooks';

// JSX declaration for the Lit web component in Preact
declare module 'preact' {
  namespace JSX {
    interface IntrinsicElements {
      'intlayer-content-selector-wrapper': HTMLAttributes<HTMLElement> & {
        'key-path'?: string;
        'dictionary-key'?: string;
      };
    }
  }
}

export type ContentSelectorWrapperProps = NodeProps &
  Omit<HTMLAttributes<HTMLDivElement>, 'children'>;

export const ContentSelector: FunctionalComponent<
  ContentSelectorWrapperProps
> = ({ children, dictionaryKey, keyPath }) => {
  useEffect(() => {
    if (
      process.env['INTLAYER_EDITOR_ENABLED'] === 'false' ||
      !isEnabled ||
      typeof window === 'undefined'
    )
      return;
    import('@intlayer/editor').then(({ defineIntlayerElements }) => {
      defineIntlayerElements();
    });
  }, [isEnabled]);

  if (process.env['INTLAYER_EDITOR_ENABLED'] === 'false' || !isEnabled) {
    return children;
  }

  return (
    <intlayer-content-selector-wrapper
      key-path={JSON.stringify(keyPath)}
      dictionary-key={dictionaryKey}
    >
      {children}
    </intlayer-content-selector-wrapper>
  );
};

// packages/solid-intlayer/src/editor/ContentSelector.tsx
import type { NodeProps } from '@intlayer/core/interpreter';
import { isEnabled } from '@intlayer/editor/isEnabled';
import type { Component, JSX } from 'solid-js';
import { Dynamic } from 'solid-js/web';

// JSX declaration for the Lit web components
declare module 'solid-js' {
  namespace JSX {
    interface IntrinsicElements {
      'intlayer-content-selector-wrapper': JSX.HTMLAttributes<HTMLElement> & {
        'key-path'?: string;
        'dictionary-key'?: string;
      };
    }
  }
}

export type ContentSelectorWrapperProps = NodeProps &
  Omit<JSX.HTMLAttributes<HTMLDivElement>, 'children'> & {
    children?: JSX.Element;
  };

export const ContentSelector: Component<ContentSelectorWrapperProps> = (
  props
) => {
  if (process.env['INTLAYER_EDITOR_ENABLED'] === 'false' || !isEnabled) {
    return props.children;
  }

  return (
    <Dynamic
      component="intlayer-content-selector-wrapper"
      attr:key-path={JSON.stringify(props.keyPath)}
      attr:dictionary-key={props.dictionaryKey}
    >
      {props.children}
    </Dynamic>
  );
};
