// packages/solid-intlayer/src/format/usePercentage.ts
import { percentage } from '@intlayer/core/formatters';
import { useContext } from 'solid-js';
import { IntlayerClientContext } from '../client/IntlayerContext';

/**
 * Solid client hook that provides a localized percentage formatter.
 */
export const usePercentage = () => {
  const { locale } = useContext(IntlayerClientContext) ?? {};

  return (...args: Parameters<typeof percentage>) =>
    percentage(args[0], {
      ...args[1],
      locale: args[1]?.locale ?? locale(),
    });
};

// packages/react-intlayer/src/client/format/usePercentage.ts
'use client';

import { percentage } from '@intlayer/core/formatters';
import { useCallback, useContext } from 'react';
import { IntlayerClientContext } from '../IntlayerContext';

/**
 * React hook to provide a percentage formatter function
 * based on the current application locale.
 *
 * This hook retrieves the active locale using {@link useLocaleBase}
 * and memoizes a `createPercentage` instance for that locale.
 *
 * @example
 * ```tsx
 * const formatPercentage = usePercentage();
 *
 * const result = formatPercentage(0.875, { maximumFractionDigits: 1 });
 * // "87.5%" (depending on locale)
 * ```
 *
 * @returns {(value: string | number, options?: Omit<PercentageOptions, "value">) => string}
 * A function that formats numbers or numeric strings into localized percentages.
 */
export const usePercentage = () => {
  const { locale } = useContext(IntlayerClientContext) ?? {};

  return useCallback(
    (...args: Parameters<typeof percentage>) =>
      percentage(args[0], {
        ...args[1],
        locale: args[1]?.locale ?? locale,
      }),
    [locale]
  );
};
