// packages/solid-intlayer/src/editor/contexts/ConfigurationContext.tsx
import { type IntlayerConfig } from '@intlayer/config/client';
import { MessageKey } from '@intlayer/editor';
import {
  type Component,
  type ParentProps,
  createContext,
  useContext,
} from 'solid-js';
import { useCrossFrameState } from './useCrossFrameState';

const ConfigurationStatesContext = createContext<IntlayerConfig | undefined>(
  undefined
);

export const useConfigurationState = () =>
  useCrossFrameState<IntlayerConfig>(
    MessageKey.INTLAYER_CONFIGURATION,
    undefined,
    {
      receive: false,
      emit: true,
    }
  );

export type ConfigurationProviderProps = ParentProps<{
  configuration?: IntlayerConfig;
}>;

export const ConfigurationProvider: Component<ConfigurationProviderProps> = (
  props
) => (
  <ConfigurationStatesContext.Provider value={props.configuration}>
    {props.children}
  </ConfigurationStatesContext.Provider>
);

export const useConfiguration = () => useContext(ConfigurationStatesContext);

// packages/preact-intlayer/src/editor/ConfigurationContext.tsx
'use client';

import type { IntlayerConfig } from '@intlayer/config/client';
import { MessageKey } from '@intlayer/editor';
import {
  createContext,
  type FC,
  type PropsWithChildren,
  useContext,
} from 'preact/compat';
import { useCrossFrameState } from './useCrossFrameState';

const ConfigurationStatesContext = createContext<IntlayerConfig | undefined>(
  undefined
);

export const useConfigurationState = () =>
  useCrossFrameState<IntlayerConfig>(
    MessageKey.INTLAYER_CONFIGURATION,
    undefined,
    {
      receive: false,
      emit: true,
    }
  );

export type ConfigurationProviderProps = {
  configuration?: IntlayerConfig;
};

export const ConfigurationProvider: FC<
  PropsWithChildren<ConfigurationProviderProps>
> = ({ children, configuration }) => (
  <ConfigurationStatesContext.Provider value={configuration}>
    {children}
  </ConfigurationStatesContext.Provider>
);

export const useConfiguration = () => useContext(ConfigurationStatesContext);
