// packages/solid-intlayer/src/editor/ContentSelectorWrapper.tsx
'use client';

import { isSameKeyPath, type NodeProps } from '@intlayer/core';
import { createMemo, type Component, type JSX } from 'solid-js';
import { useIntlayerContext } from '../client';
import { ContentSelector } from '../UI/ContentSelector';
import { useEditorEnabled, useFocusDictionary } from './contexts';

export type ContentSelectorWrapperProps = NodeProps &
  Omit<JSX.HTMLAttributes<HTMLDivElement>, 'children'> & {
    children?: JSX.Element;
  };

const ContentSelectorWrapperContent: Component<ContentSelectorWrapperProps> = (
  props
) => {
  const { focusedContent, setFocusedContent } = useFocusDictionary();

  const handleSelect = () =>
    setFocusedContent({
      dictionaryKey: props.dictionaryKey,
      keyPath: props.keyPath,
    });

  const isSelected = createMemo(
    () =>
      (focusedContent?.dictionaryKey === props.dictionaryKey &&
        (focusedContent?.keyPath?.length ?? 0) > 0 &&
        isSameKeyPath(focusedContent?.keyPath ?? [], props.keyPath)) ??
      false
  );

  return (
    <ContentSelector onPress={handleSelect} isSelecting={isSelected()}>
      {props.children}
    </ContentSelector>
  );
};

export const ContentSelectorRenderer: Component<ContentSelectorWrapperProps> = (
  props
) => {
  const { enabled } = useEditorEnabled();
  const { disableEditor } = useIntlayerContext();

  if (enabled() && !disableEditor) {
    return (
      <ContentSelectorWrapperContent {...props}>
        {props.children}
      </ContentSelectorWrapperContent>
    );
  }

  return props.children;
};

// packages/preact-intlayer/src/editor/ContentSelectorWrapper.tsx
'use client';

import { type NodeProps, isSameKeyPath } from '@intlayer/core';
import {
  type FC,
  type HTMLAttributes,
  useCallback,
  useMemo,
} from 'preact/compat';
import { useIntlayerContext } from '../client';
import { ContentSelector } from '../UI/ContentSelector';
import { useEditorEnabled } from './EditorEnabledContext';
import { useFocusDictionary } from './FocusDictionaryContext';

export type ContentSelectorWrapperProps = NodeProps &
  Omit<HTMLAttributes<HTMLDivElement>, 'children'>;

const ContentSelectorWrapperContent: FC<ContentSelectorWrapperProps> = ({
  children,
  dictionaryKey,
  keyPath,
}) => {
  const { focusedContent, setFocusedContent } = useFocusDictionary();

  const handleSelect = useCallback(
    () =>
      setFocusedContent({
        dictionaryKey,
        keyPath,
      }),
    [dictionaryKey, keyPath]
  );

  const isSelected = useMemo(
    () =>
      (focusedContent?.dictionaryKey === dictionaryKey &&
        (focusedContent?.keyPath?.length ?? 0) > 0 &&
        isSameKeyPath(focusedContent?.keyPath ?? [], keyPath)) ??
      false,
    [focusedContent, keyPath, dictionaryKey]
  );

  return (
    <ContentSelector onPress={handleSelect} isSelecting={isSelected}>
      {children}
    </ContentSelector>
  );
};

export const ContentSelectorRenderer: FC<ContentSelectorWrapperProps> = ({
  children,
  ...props
}) => {
  const { enabled } = useEditorEnabled();
  const { disableEditor } = useIntlayerContext();

  if (enabled && !disableEditor) {
    return (
      <ContentSelectorWrapperContent {...props}>
        {children}
      </ContentSelectorWrapperContent>
    );
  }

  return children;
};
