// packages/solid-intlayer/src/html/HTMLProvider.tsx
import {
  type Component,
  createContext,
  type ParentProps,
  useContext,
} from 'solid-js';
import type { HTMLComponents } from './types';

type HTMLProviderValue = {
  components?: HTMLComponents<'permissive', {}>;
};

const HTMLContext = createContext<HTMLProviderValue>();

export const useHTMLContext = () => useContext(HTMLContext);

export type HTMLProviderProps = ParentProps<{
  components?: HTMLComponents<'permissive', {}>;
}>;

export const HTMLProvider: Component<HTMLProviderProps> = (props) => {
  return (
    <HTMLContext.Provider
      value={{
        components: props.components,
      }}
    >
      {props.children}
    </HTMLContext.Provider>
  );
};

// packages/react-intlayer/src/html/HTMLProvider.tsx
'use client';

import {
  createContext,
  type FC,
  type PropsWithChildren,
  useContext,
} from 'react';
import type { HTMLComponents } from './HTMLComponentTypes';

type HTMLContextValue = {
  components?: HTMLComponents<'permissive', {}>;
};

type HTMLProviderProps = PropsWithChildren<{
  /**
   * Component overrides for HTML tags.
   */
  components?: HTMLComponents<'permissive', {}>;
}>;

const HTMLContext = createContext<HTMLContextValue | undefined>(undefined);

export const useHTMLContext = () => useContext(HTMLContext);

export const HTMLProvider: FC<HTMLProviderProps> = ({
  children,
  components,
}) => (
  <HTMLContext.Provider value={{ components }}>{children}</HTMLContext.Provider>
);
