// packages/angular-intlayer/src/format/useUnit.ts
import { computed, inject } from '@angular/core';
import { units } from '@intlayer/core/formatters';
import { IntlayerProvider } from '../client/installIntlayer';

export const useUnit = () => {
  const intlayer = inject(IntlayerProvider);

  return computed(
    () =>
      (...args: Parameters<typeof units>) =>
        units(args[0], {
          ...args[1],
          locale: args[1]?.locale ?? intlayer.locale(),
        })
  );
};

// packages/lit-intlayer/src/format/useUnit.ts
import { units } from '@intlayer/core/formatters';
import type { ReactiveController, ReactiveControllerHost } from 'lit';
import { getIntlayerClient } from '../client/installIntlayer';

class UnitController implements ReactiveController {
  private readonly host: ReactiveControllerHost;
  private _unsubscribe: (() => void) | null = null;
  value: (...args: Parameters<typeof units>) => string;

  constructor(host: ReactiveControllerHost) {
    this.host = host;
    const client = getIntlayerClient();
    this.value = (...args) =>
      units(args[0], { ...args[1], locale: args[1]?.locale ?? client.locale });

    host.addController(this);
  }

  hostConnected(): void {
    const client = getIntlayerClient();
    this._unsubscribe = client.subscribe((newLocale) => {
      this.value = (...args) =>
        units(args[0], {
          ...args[1],
          locale: args[1]?.locale ?? newLocale,
        });
      this.host.requestUpdate();
    });
  }

  hostDisconnected(): void {
    this._unsubscribe?.();
    this._unsubscribe = null;
  }
}

export const useUnit = (host: ReactiveControllerHost): UnitController =>
  new UnitController(host);
