// packages/react-intlayer/src/editor/ContentSelector.tsx
'use client';

import type { NodeProps } from '@intlayer/core/interpreter';
import { isEnabled } from '@intlayer/editor/isEnabled';
import { createElement, type FC, type HTMLAttributes } from 'react';

export type ContentSelectorProps = NodeProps &
  Omit<HTMLAttributes<HTMLDivElement>, 'children'>;

export const ContentSelector: FC<ContentSelectorProps> = ({
  children,
  dictionaryKey,
  keyPath,
}) => {
  if (isEnabled) {
    return createElement(
      'intlayer-content-selector-wrapper',
      {
        'key-path': JSON.stringify(keyPath),
        'dictionary-key': dictionaryKey,
      },
      children
    );
  }

  return children;
};

// packages/vue-intlayer/src/editor/ContentSelector.vue
<script setup lang="ts">
import type { NodeProps } from '@intlayer/core/interpreter';
import { isEnabled } from '@intlayer/editor/isEnabled';
import type { HTMLAttributes } from 'vue';

type Props = NodeProps & /* @vue-ignore */ Omit<HTMLAttributes, 'children'>;
const props = defineProps<Props>();
</script>

<template>
  <intlayer-content-selector-wrapper
    v-if="isEnabled"
    :key-path="JSON.stringify(props.keyPath)"
    :dictionary-key="props.dictionaryKey"
  >
    <slot />
  </intlayer-content-selector-wrapper>
  <slot v-else />
</template>
