// packages/angular-intlayer/src/editor/EditedContentRenderer.component.ts
import { CommonModule } from '@angular/common';
import { Component, computed, Input, signal } from '@angular/core';
import { getBasePlugins, getContent } from '@intlayer/core/interpreter';
import type { Locale } from '@intlayer/types/allLocales';
import type { ContentNode } from '@intlayer/types/dictionary';
import type { KeyPath } from '@intlayer/types/keyPath';
import { useEditedContentRenderer } from './useEditedContentRenderer';

export interface EditedContentRendererProps {
  dictionaryKey: string;
  keyPath: KeyPath[];
  locale?: Locale;
}

@Component({
  selector: 'app-edited-content-renderer',
  standalone: true,
  imports: [CommonModule],
  template: ` <span [innerHTML]="renderedContent()"></span> `,
})
export class EditedContentRendererComponent {
  @Input() dictionaryKey!: string;
  @Input() keyPath!: KeyPath[];
  @Input() locale?: Locale;

  private fallback = signal('');

  private rawContent = computed(() => {
    return useEditedContentRenderer(
      this.dictionaryKey,
      this.keyPath,
      this.fallback
    );
  });

  /**
   * Object → getContent → string, same as the React version.
   */
  renderedContent = computed(() => {
    const rawContentValue = this.rawContent();

    if (typeof rawContentValue === 'object' && rawContentValue !== null) {
      const transformed = getContent(
        rawContentValue as ContentNode,
        {
          dictionaryKey: this.dictionaryKey,
          keyPath: this.keyPath,
          locale: this.locale,
        },
        getBasePlugins(this.locale)
      );

      if (typeof transformed !== 'string') {
        console.error(
          `Incorrect edited content format. Content type: ${typeof transformed}. Expected string. Value ${JSON.stringify(
            transformed
          )}`
        );
        return this.fallback();
      }
      return transformed;
    }

    return rawContentValue() as string;
  });
}

// packages/vue-intlayer/src/editor/EditedContentRenderer.vue
<script setup lang="ts">
import { getBasePlugins, getContent } from '@intlayer/core/interpreter';
import type { Locale } from '@intlayer/types/allLocales';
import type { ContentNode } from '@intlayer/types/dictionary';
import type { KeyPath } from '@intlayer/types/keyPath';
import { computed, useSlots } from 'vue';
import { useEditedContentRenderer } from './useEditedContentRenderer';

type Props = {
  dictionaryKey: string;
  keyPath: KeyPath[];
  locale?: Locale;
};

const props = defineProps<Props>();
const slots = useSlots();

/**
 * <slot> replaces React "children".
 * If no slot content is provided, fall back to an empty string.
 */
const fallback = computed(() => {
  const vnodes = slots.default?.() ?? [];
  return vnodes
    .map((v) => (typeof v.children === 'string' ? v.children : ''))
    .join('');
});

const rawContent = useEditedContentRenderer(
  props.dictionaryKey,
  props.keyPath,
  fallback
);

/**
 * Object → getContent → string, same as the React version.
 */
const renderedContent = computed(() => {
  if (typeof rawContent.value === 'object' && rawContent.value !== null) {
    const transformed = getContent(
      rawContent.value as ContentNode,
      { ...props, locale: props.locale },
      getBasePlugins(props.locale)
    );

    if (typeof transformed !== 'string') {
      console.error(
        `Incorrect edited content format. Content type: ${typeof transformed}. Expected string. Value ${JSON.stringify(
          transformed
        )}`
      );
      return fallback.value;
    }
    return transformed;
  }

  return rawContent.value as string;
});
</script>

<template>
  <!-- Just render the text/HTML -->
  <renderedContent />
</template>
