// packages/angular-intlayer/src/plugins.ts
import { signal, untracked } from '@angular/core';
import { editor, internationalization } from '@intlayer/config/built';
import {
  bindInsertedValues,
  conditionPlugin,
  type DeepTransformContent as DeepTransformContentCore,
  enumerationPlugin,
  fallbackPlugin,
  filePlugin,
  genderPlugin,
  getInsertion,
  type IInterpreterPluginState as IInterpreterPluginStateCore,
  isInterpolableWrapperNode,
  nestedPlugin,
  type Plugins,
  pluralPlugin,
  resolveInterpreterLocale,
  selectPlugin,
  transformInterpolableNode,
  translationPlugin,
} from '@intlayer/core/interpreter';
import type { MarkdownContent } from '@intlayer/core/markdown';
import { compile, getMarkdownMetadata } from '@intlayer/core/markdown';
import type { HTMLContent, InsertionContent } from '@intlayer/core/transpiler';
import type { KeyPath } from '@intlayer/types/keyPath';
import type {
  DeclaredLocales,
  LocalesValues,
} from '@intlayer/types/module_augmentation';
import type { NodeType } from '@intlayer/types/nodeType';
import * as NodeTypes from '@intlayer/types/nodeType';
import { reportExposure } from './analytics/exposureSink';
import { ContentSelectorWrapperComponent } from './editor/ContentSelector.component';
import { type IntlayerNode, renderIntlayerNode } from './renderIntlayerNode';

type MarkdownRendererModule = Pick<
  typeof import('./markdown/installIntlayerMarkdown'),
  'htmlRuntime' | 'useMarkdown'
>;

/**
 * Code-split markdown renderer, held in a signal.
 *
 * The chunk loads asynchronously, so the first dictionary evaluation may run
 * before it lands. `getPlugins` reads this signal inside the `computed` of
 * `useIntlayer`/`useDictionary`, which makes that computed depend on it: nodes
 * stringify to their raw source until the module resolves, then the signal
 * flip re-evaluates the dictionary and every binding re-renders with compiled
 * HTML. This is the Angular counterpart of the `Suspense` boundary the React
 * and Solid packages wrap their markdown renderer in.
 */
const markdownRendererModule = signal<MarkdownRendererModule | null>(null);

if (
  process.env.INTLAYER_NODE_TYPE_MARKDOWN !== 'false' ||
  process.env.INTLAYER_NODE_TYPE_HTML !== 'false'
) {
  void import('./markdown/installIntlayerMarkdown')
    .then((module) => markdownRendererModule.set(module))
    .catch(() => {});
}

/** ---------------------------------------------
 *  UTILS
 *  --------------------------------------------- */

const createRuntimeWithOverides = (baseRuntime: any, overrides: any) => ({
  ...baseRuntime,
  createElement: (tag: string, props: any, ...children: any[]) => {
    const override = overrides?.[tag];

    if (override) {
      const newProps = { ...props, ...override };

      // Merge class attributes intelligently
      const originalClass = props?.class || props?.className;
      const overrideClass = override.class || override.className;

      if (originalClass && overrideClass) {
        newProps.class = `${originalClass} ${overrideClass}`;
        newProps.className = undefined;
      }

      return baseRuntime.createElement(tag, newProps, ...children);
    }

    return baseRuntime.createElement(tag, props, ...children);
  },
});

/**
 * Compiles a markdown/HTML source to an HTML string with the code-split
 * runtime, or returns the raw source while the renderer chunk is still
 * loading. Runs at stringify time, so a node kept outside any reactive
 * context still picks the renderer up once it has landed.
 */
const compileToHtml = (
  source: string,
  components?: Record<string, unknown>
): string => {
  const rendererModule = untracked(markdownRendererModule);

  if (!rendererModule) return source;

  const runtime = components
    ? createRuntimeWithOverides(rendererModule.htmlRuntime, components)
    : rendererModule.htmlRuntime;

  return compile(source, { runtime }) as string;
};

/** ---------------------------------------------
 *  INTLAYER NODE PLUGIN
 *  --------------------------------------------- */

export type IntlayerNodeCond<T> = T extends number | string
  ? IntlayerNode<T>
  : never;

export type { IntlayerNode };

/** Translation plugin. Replaces node with a locale string if nodeType = Translation. */
export const intlayerNodePlugins: Plugins = {
  id: 'intlayer-node-plugin',
  canHandle: (node) =>
    typeof node === 'bigint' ||
    typeof node === 'string' ||
    typeof node === 'number',
  transform: (_node, props) => {
    const { children, dictionaryKey, keyPath } = props;

    // Node-level analytics: record which content is resolved for display.
    // No-op (and dead-code-eliminated) when analytics is disabled.
    if (process.env.INTLAYER_ANALYTICS_ENABLED !== 'false') {
      reportExposure({
        dictionaryKey,
        keyPath,
        locale: props.locale,
        nodeType: 'text',
      });
    }

    return renderIntlayerNode({
      value: children,
      children: () => ({
        component:
          process.env.INTLAYER_EDITOR_ENABLED === 'false' || !editor.enabled
            ? children
            : ContentSelectorWrapperComponent,
        props: { dictionaryKey, keyPath },
        children: children,
      }),
    });
  },
};

/**
 * MARKDOWN PLUGIN
 */

export type MarkdownStringCond<T> = T extends string
  ? IntlayerNode<string, { metadata: DeepTransformContent<string> }>
  : never;

/** Markdown string plugin. Replaces string node with a component that render the markdown. */
export const markdownStringPlugin: Plugins =
  process.env.INTLAYER_NODE_TYPE_MARKDOWN === 'false'
    ? fallbackPlugin
    : {
        id: 'markdown-string-plugin',
        canHandle: (node) => typeof node === 'string',
        transform: (node: string, props, deepTransformNode) => {
          const {
            plugins, // Removed to avoid next error - Functions cannot be passed directly to Client Components
            ...rest
          } = props;

          const metadata = getMarkdownMetadata(node) ?? {};

          const metadataPlugins: Plugins = {
            id: 'markdown-metadata-plugin',
            canHandle: (metadataNode) =>
              typeof metadataNode === 'string' ||
              typeof metadataNode === 'number' ||
              typeof metadataNode === 'boolean' ||
              !metadataNode,
            transform: (metadataNode, props) =>
              renderIntlayerNode({
                ...props,
                value: metadataNode,
                children: node,
              }),
          };

          // Transform metadata while keeping the same structure
          const metadataNodes = deepTransformNode(metadata, {
            plugins: [metadataPlugins],
            dictionaryKey: rest.dictionaryKey,
            keyPath: [],
          });

          const renderMarkdown = (components?: any) =>
            untracked(markdownRendererModule)
              ?.useMarkdown()
              .renderMarkdown(node, components) ?? node;

          const render = (components?: any): any => {
            const toHtml = () => compileToHtml(node, components);

            return renderIntlayerNode({
              ...rest,
              value: node,
              children:
                process.env.INTLAYER_EDITOR_ENABLED === 'false' ||
                !editor.enabled
                  ? () => renderMarkdown(components)
                  : () => ({
                      component: ContentSelectorWrapperComponent,
                      props: {
                        dictionaryKey: rest.dictionaryKey,
                        keyPath: rest.keyPath,
                        ...components,
                      },
                      children: () => renderMarkdown(components),
                    }),
              additionalProps: {
                metadata: metadataNodes,
                toString: toHtml,
                [Symbol.toPrimitive]: toHtml,
                use: (newComponents?: any) =>
                  render({ ...components, ...newComponents }),
              },
            });
          };

          return render();
        },
      };

export type MarkdownCond<T, _S, _L extends LocalesValues> = T extends {
  nodeType: NodeType | string;
  [NodeTypes.MARKDOWN]: infer M;
  tags?: infer U;
  metadata?: infer V;
}
  ? IntlayerNode<
      M,
      {
        use: (components?: Record<keyof U, any>) => any;
        metadata: DeepTransformContent<V>;
      }
    >
  : never;

export const markdownPlugin: Plugins =
  process.env.INTLAYER_NODE_TYPE_MARKDOWN === 'false'
    ? fallbackPlugin
    : {
        id: 'markdown-plugin',
        canHandle: (node) =>
          typeof node === 'object' && node?.nodeType === NodeTypes.MARKDOWN,
        transform: (node: MarkdownContent, props, deepTransformNode) => {
          const newKeyPath: KeyPath[] = [
            ...props.keyPath,
            {
              type: NodeTypes.MARKDOWN,
            },
          ];

          const children = node[NodeTypes.MARKDOWN];

          return deepTransformNode(children, {
            ...props,
            children,
            keyPath: newKeyPath,
            plugins: [markdownStringPlugin, ...(props.plugins ?? [])],
          });
        },
      };

/** ---------------------------------------------
 *  HTML PLUGIN
 *  --------------------------------------------- */

/**
 * HTML conditional type.
 *
 * This ensures type safety:
 * - `html('<div>Hello <CustomComponent /></div>').use({ CustomComponent: ... })` - optional but typed
 */
export type HTMLPluginCond<T, _S, _L> = T extends {
  nodeType: NodeType | string;
  [NodeTypes.HTML]: infer I;
  tags?: infer U;
}
  ? IntlayerNode<
      I,
      {
        use: (components?: Record<keyof U, any>) => any;
      }
    >
  : never;

/** HTML plugin. Replaces node with a function that takes components => IntlayerNode. */
export const htmlPlugin: Plugins =
  process.env.INTLAYER_NODE_TYPE_HTML === 'false'
    ? fallbackPlugin
    : {
        id: 'html-plugin',
        canHandle: (node) =>
          typeof node === 'object' && node?.nodeType === NodeTypes.HTML,

        transform: (node: HTMLContent<string>, props) => {
          const html = node[NodeTypes.HTML];
          const { plugins, ...rest } = props;

          // Type-safe render function that accepts properly typed components
          const render = (userComponents?: any): any => {
            // Without component overrides the source is already HTML
            const toHtml = () =>
              !userComponents || Object.keys(userComponents).length === 0
                ? String(html)
                : compileToHtml(String(html), userComponents);

            return renderIntlayerNode({
              ...rest,
              value: html,
              children:
                process.env.INTLAYER_EDITOR_ENABLED === 'false' ||
                !editor.enabled
                  ? html
                  : () => ({
                      component: ContentSelectorWrapperComponent,
                      props: {
                        dictionaryKey: rest.dictionaryKey,
                        keyPath: rest.keyPath,
                        ...userComponents,
                      },
                      children: html,
                    }),
              additionalProps: {
                toString: toHtml,
                [Symbol.toPrimitive]: toHtml,
                use: (newComponents?: any) =>
                  render({ ...userComponents, ...newComponents }),
              },
            });
          };

          return render();
        },
      };

/** ---------------------------------------------
 *  INSERTION PLUGIN
 *  --------------------------------------------- */

/**
 * Insertion conditional type.
 */
export type InsertionPluginCond<T, S, L extends LocalesValues> = T extends {
  nodeType: NodeType | string;
  [NodeTypes.INSERTION]: infer Content;
}
  ? (
      args: Record<string, string | number>
    ) => Content extends string
      ? string
      : DeepTransformContentCore<Content, S, L>
  : never;

export const insertionPlugin: Plugins =
  process.env.INTLAYER_NODE_TYPE_INSERTION === 'false'
    ? fallbackPlugin
    : {
        id: 'insertion-plugin',
        canHandle: (node) =>
          typeof node === 'object' && node?.nodeType === NodeTypes.INSERTION,
        transform: (node: InsertionContent, props, deepTransformNode) => {
          const { plugins, ...rest } = props;
          const content = node[NodeTypes.INSERTION];

          const newKeyPath: KeyPath[] = [
            ...props.keyPath,
            {
              type: NodeTypes.INSERTION,
            },
          ];

          // `html()`/`markdown()` nodes carry their `{{ … }}` placeholders
          // inside a raw string. Interpolate into that string, then re-run the
          // transform so the html/markdown renderer applies afterwards.
          if (isInterpolableWrapperNode(content)) {
            return (args: Record<string, string | number> = {}) =>
              transformInterpolableNode(
                content,
                args,
                { ...props, keyPath: newKeyPath },
                props.plugins,
                deepTransformNode
              );
          }

          // Container content (`insert(enu(…))`, `insert(plural(…))`, …):
          // interpolate every branch string, then bind the values to the
          // selector so the call reads `(values) => (selector) => content`.
          if (typeof content === 'object' && content !== null) {
            return (args: Record<string, string | number> = {}) => {
              const insertionStringPlugin: Plugins = {
                id: 'insertion-string-plugin',
                canHandle: (branch) =>
                  typeof branch === 'string' ||
                  isInterpolableWrapperNode(branch),
                transform: (branch, subProps, deepTransformBranch) => {
                  if (isInterpolableWrapperNode(branch)) {
                    return transformInterpolableNode(
                      branch,
                      args,
                      subProps,
                      plugins,
                      deepTransformBranch
                    );
                  }

                  const interpolated = getInsertion(branch, args);

                  return deepTransformBranch(interpolated, {
                    ...subProps,
                    children: interpolated,
                    plugins,
                  });
                },
              };

              const result = deepTransformNode(content, {
                ...props,
                children: content,
                keyPath: [...props.keyPath, { type: NodeTypes.INSERTION }],
                plugins: [insertionStringPlugin, ...(plugins ?? [])],
              });

              return bindInsertedValues(content, result, args, true);
            };
          }

          // Return a function that performs the interpolation
          const render = (args: Record<string, string | number> = {}) => {
            let text = content as string;
            if (args) {
              Object.entries(args).forEach(([key, value]) => {
                text = text.replace(
                  new RegExp(`{{\\s*${key}\\s*}}`, 'g'),
                  String(value)
                );
              });
            }
            return text;
          };

          return renderIntlayerNode({
            ...rest,
            value: render as any,
            children: render,
          });
        },
      };

export interface IInterpreterPluginAngular<T, S, L extends LocalesValues> {
  angularIntlayerNode: IntlayerNodeCond<T>;
  angularMarkdown: MarkdownCond<T, S, L>;
  angularHtml: HTMLPluginCond<T, S, L>;
  angularInsertion: InsertionPluginCond<T, S, L>;
}

/**
 * Insert this type as param of `DeepTransformContent` to avoid `intlayer` package pollution.
 *
 * Otherwise the the `angular-intlayer` plugins will override the types of `intlayer` functions.
 */
export type IInterpreterPluginState = Omit<
  IInterpreterPluginStateCore,
  'insertion' // Remove insertion type from core package
> & {
  angularIntlayerNode: true;
  angularMarkdown: true;
  angularHtml: true;
  angularInsertion: true;
};

export type DeepTransformContent<
  T,
  L extends LocalesValues = DeclaredLocales,
> = DeepTransformContentCore<T, IInterpreterPluginState, L>;

const pluginsCache = new Map<string, Plugins[]>();

/**
 * Get the plugins array for Angular content transformation.
 * This function is used by both getIntlayer and getDictionary to ensure consistent plugin configuration.
 */
export const getPlugins = (
  locale?: LocalesValues,
  fallback: boolean = true
): Plugins[] => {
  const currentLocale = resolveInterpreterLocale(locale);
  // Tracked read: called inside the dictionary `computed` of the hooks, so the
  // computed re-evaluates once the renderer chunk lands. The core interpreter
  // memoizes transformed content per plugin-array identity, and the transform
  // itself is lazy (property getters resolved from the template), so handing
  // out a fresh array is what discards the proxies built while pending and
  // gives every binding a new value to re-render.
  const isRendererLoaded = markdownRendererModule() !== null;
  const cacheKey = `${currentLocale}_${fallback}_${isRendererLoaded}`;

  if (pluginsCache.has(cacheKey)) {
    return pluginsCache.get(cacheKey)!;
  }

  const plugins = [
    // First: most nodes are plain strings, which every other plugin rejects
    intlayerNodePlugins,
    translationPlugin(
      currentLocale,
      fallback ? internationalization.defaultLocale : undefined
    ),
    enumerationPlugin,
    pluralPlugin(currentLocale),
    conditionPlugin,
    nestedPlugin(currentLocale),
    filePlugin,
    genderPlugin,
    selectPlugin,
    markdownPlugin,
    htmlPlugin,
    insertionPlugin,
  ] as Plugins[];

  // Plugins disabled at build time never match: skip them on every node
  const enabledPlugins = plugins.filter((plugin) => plugin !== fallbackPlugin);

  pluginsCache.set(cacheKey, enabledPlugins);

  return enabledPlugins;
};

// packages/react-intlayer/src/plugins.tsx
import { editor, internationalization } from '@intlayer/config/built';
import {
  conditionPlugin,
  type DeepTransformContent as DeepTransformContentCore,
  enumerationPlugin,
  fallbackPlugin,
  filePlugin,
  genderPlugin,
  type IInterpreterPluginState as IInterpreterPluginStateCore,
  isInterpolableWrapperNode,
  nestedPlugin,
  type Plugins,
  pluralPlugin,
  resolveInsertedSelector,
  selectPlugin,
  splitInsertionTemplate,
  transformInterpolableNode,
  translationPlugin,
} from '@intlayer/core/interpreter';
import { getMarkdownMetadata } from '@intlayer/core/markdown';
import type {
  HTMLContent,
  InsertionContent,
  MarkdownContent,
} from '@intlayer/core/transpiler';
import type { KeyPath } from '@intlayer/types/keyPath';
import type {
  DeclaredLocales,
  LocalesValues,
} from '@intlayer/types/module_augmentation';
import type { NodeType } from '@intlayer/types/nodeType';
import * as NodeTypes from '@intlayer/types/nodeType';
import {
  createElement,
  type FC,
  Fragment,
  type ReactElement,
  type ReactNode,
} from 'react';
import { reportExposure } from './analytics/exposureSink';
import { useLoadDynamic } from './client/useLoadDynamic';
import { ContentSelector } from './editor/ContentSelector';
import type { HTMLComponents } from './html/HTMLComponentTypes';
import { type IntlayerNode, renderIntlayerNode } from './IntlayerNode';
import { renderReactElement } from './reactElement/renderReactElement';

const markdownRendererModulePromise =
  process.env.INTLAYER_NODE_TYPE_MARKDOWN !== 'false'
    ? import('./markdown/MarkdownRendererPlugin').then(
        (m) => m.MarkdownRendererPlugin
      )
    : null;

const htmlRendererModulePromise =
  process.env.INTLAYER_NODE_TYPE_HTML !== 'false'
    ? import('./html/HTMLRendererPlugin').then((m) => m.HTMLRendererPlugin)
    : null;

// These preloads are read later by `useLoadDynamic`, so the rejection must stay
// on the promise: a `.catch()` chained into it would resolve with `undefined`
// and be mistaken for a loaded module. Handle it on the side instead, so an
// aborted chunk load never escapes as an unhandled rejection.
markdownRendererModulePromise?.catch(() => {});
htmlRendererModulePromise?.catch(() => {});

/** ---------------------------------------------
 *  INTLAYER NODE PLUGIN
 *  --------------------------------------------- */

export type IntlayerNodeCond<T> = T extends number | string
  ? IntlayerNode<T>
  : never;

/** Translation plugin. Replaces node with a locale string if nodeType = Translation. */
export const intlayerNodePlugins: Plugins = {
  id: 'intlayer-node-plugin',
  canHandle: (node) =>
    typeof node === 'bigint' ||
    typeof node === 'string' ||
    typeof node === 'number',
  transform: (_node, props) => {
    // Node-level analytics: record which content is resolved for display.
    // No-op (and dead-code-eliminated) when analytics is disabled.
    if (process.env.INTLAYER_ANALYTICS_ENABLED !== 'false') {
      reportExposure({
        dictionaryKey: props.dictionaryKey,
        keyPath: props.keyPath,
        locale: props.locale,
        nodeType: 'text',
      });
    }

    // Props are only forwarded to the editor selector: copying them for every
    // leaf would cost an allocation per rendered string
    if (process.env.INTLAYER_EDITOR_ENABLED !== 'false' && editor.enabled) {
      const {
        plugins, // Removed to avoid next error - Functions cannot be passed directly to Client Components
        ...rest
      } = props;

      return renderIntlayerNode({
        value: rest.children,
        children: <ContentSelector {...rest}>{rest.children}</ContentSelector>,
      });
    }

    return renderIntlayerNode({
      value: props.children,
      children: props.children,
    });
  },
};

/** ---------------------------------------------
 *  REACT NODE PLUGIN
 *  --------------------------------------------- */

export type ReactNodeCond<T> = T extends {
  props: any;
  key: any;
}
  ? ReactNode
  : never;

/** Translation plugin. Replaces node with a locale string if nodeType = Translation. */
export const reactNodePlugins: Plugins =
  process.env.INTLAYER_NODE_TYPE_REACT_NODE === 'false'
    ? fallbackPlugin
    : {
        id: 'react-node-plugin',
        canHandle: (node) =>
          typeof node === 'object' &&
          typeof node?.props !== 'undefined' &&
          typeof node.key !== 'undefined',

        transform: (
          node,
          {
            plugins, // Removed to avoid next error - Functions cannot be passed directly to Client Components
            ...rest
          }
        ) => {
          if (process.env.INTLAYER_ANALYTICS_ENABLED !== 'false') {
            reportExposure({
              dictionaryKey: rest.dictionaryKey,
              keyPath: rest.keyPath,
              locale: rest.locale,
              nodeType: 'react-node',
            });
          }

          return renderIntlayerNode({
            ...rest,
            value: '[[react-element]]',
            children:
              process.env.INTLAYER_EDITOR_ENABLED !== 'false' &&
              editor.enabled ? (
                <ContentSelector {...rest}>
                  {renderReactElement(node)}
                </ContentSelector>
              ) : (
                renderReactElement(node)
              ),
          });
        },
      };

/** ---------------------------------------------
 *  INSERTION PLUGIN
 *  --------------------------------------------- */

export type InsertionCond<T> = T extends {
  nodeType: NodeType | string;
  [NodeTypes.INSERTION]: infer I;
  fields: readonly string[];
}
  ? <V extends { [K in T['fields'][number]]: ReactNode }>(
      values: V
    ) => I extends string
      ? V[keyof V] extends string | number
        ? IntlayerNode<string>
        : IntlayerNode<ReactNode>
      : DeepTransformContent<I>
  : never;

/**
 * Split insertion string and join with React nodes using shared core logic
 */
const splitAndJoinInsertion = (
  template: string,
  values: Record<string, string | number | ReactNode>
): ReactNode => {
  const result = splitInsertionTemplate(template, values);

  if (result.isSimple) {
    // Simple string replacement
    return result.parts as string;
  }

  // Return as Fragment with proper keys
  return createElement(
    Fragment,
    null,
    ...(result.parts as any[]).map((part, index) =>
      createElement(Fragment, { key: index }, part)
    )
  );
};

/** Insertion plugin for React. Handles component/node insertion. */
export const insertionPlugin: Plugins =
  process.env.INTLAYER_NODE_TYPE_INSERTION === 'false'
    ? fallbackPlugin
    : {
        id: 'insertion-plugin',
        canHandle: (node) =>
          typeof node === 'object' && node?.nodeType === NodeTypes.INSERTION,
        transform: (node: InsertionContent, props, deepTransformNode) => {
          const newKeyPath: KeyPath[] = [
            ...props.keyPath,
            {
              type: NodeTypes.INSERTION,
            },
          ];

          const children = node[NodeTypes.INSERTION];

          /** Insertion string plugin. Replaces string node with a component that render the insertion. */
          const insertionStringPlugin: Plugins = {
            id: 'insertion-string-plugin',
            canHandle: (node) =>
              typeof node === 'string' || isInterpolableWrapperNode(node),
            transform: (node, subProps, deepTransformNode) => {
              // `html()`/`markdown()` nodes carry their `{{ … }}` placeholders
              // inside a raw string. Interpolate into that string, then re-run
              // the transform so the html/markdown renderer applies afterwards.
              // React nodes cannot be injected into a raw markup string, so
              // string interpolation (not `splitAndJoinInsertion`) is used here.
              if (isInterpolableWrapperNode(node)) {
                return (
                  values: {
                    [K in InsertionContent['fields'][number]]: string | number;
                  }
                ) =>
                  transformInterpolableNode(
                    node,
                    values,
                    subProps,
                    props.plugins,
                    deepTransformNode
                  );
              }

              const transformedResult = deepTransformNode(node, {
                ...subProps,
                children: node,
                plugins: [
                  ...(props.plugins ?? ([] as Plugins[])).filter(
                    (plugin) => plugin.id !== 'intlayer-node-plugin'
                  ),
                ],
              });

              return (
                values: {
                  [K in InsertionContent['fields'][number]]:
                    | string
                    | number
                    | ReactNode;
                }
              ) => {
                const result = splitAndJoinInsertion(transformedResult, values);

                return deepTransformNode(result, {
                  ...subProps,
                  plugins: props.plugins,
                  children: result,
                });
              };
            },
          };

          const result = deepTransformNode(children, {
            ...props,
            children,
            keyPath: newKeyPath,
            plugins: [insertionStringPlugin, ...(props.plugins ?? [])],
          });

          return resolveInsertedSelector(children, result);
        },
      };

/**
 * MARKDOWN PLUGIN
 */

export type MarkdownStringCond<T> = T extends string
  ? IntlayerNode<
      string,
      {
        metadata: DeepTransformContent<string>;
        use: (components: HTMLComponents<'permissive', {}>) => ReactNode;
      }
    >
  : never;

const MarkdownSuspenseRenderer: FC<Record<string, any>> = ({
  children,
  ...props
}) => {
  const MarkdownRendererPlugin = useLoadDynamic(
    'markdown-renderer-plugin',
    markdownRendererModulePromise!
  );
  return createElement(MarkdownRendererPlugin as any, { ...props, children });
};

/** Markdown string plugin. Replaces string node with a component that render the markdown. */
export const markdownStringPlugin: Plugins =
  process.env.INTLAYER_NODE_TYPE_MARKDOWN === 'false'
    ? fallbackPlugin
    : {
        id: 'markdown-string-plugin',
        canHandle: (node) => typeof node === 'string',
        transform: (node: string, props, deepTransformNode) => {
          const {
            plugins, // Removed to avoid next error - Functions cannot be passed directly to Client Components
            ...rest
          } = props;

          const metadata = getMarkdownMetadata(node) ?? {};

          const metadataPlugins: Plugins = {
            id: 'markdown-metadata-plugin',
            canHandle: (metadataNode) =>
              typeof metadataNode === 'string' ||
              typeof metadataNode === 'number' ||
              typeof metadataNode === 'boolean' ||
              !metadataNode,
            transform: (metadataNode, props) =>
              renderIntlayerNode({
                ...props,
                value: metadataNode,
                children:
                  process.env.INTLAYER_EDITOR_ENABLED !== 'false' &&
                  editor.enabled ? (
                    <ContentSelector {...rest}>{node}</ContentSelector>
                  ) : (
                    node
                  ),
              }),
          };

          // Transform metadata while keeping the same structure
          const metadataNodes = deepTransformNode(metadata, {
            plugins: [metadataPlugins],
            dictionaryKey: rest.dictionaryKey,
            keyPath: [],
          });

          const render = (components?: HTMLComponents) =>
            renderIntlayerNode({
              ...props,
              value: node,
              children:
                process.env.INTLAYER_EDITOR_ENABLED !== 'false' &&
                editor.enabled ? (
                  <ContentSelector {...rest}>
                    <MarkdownSuspenseRenderer {...rest} components={components}>
                      {node}
                    </MarkdownSuspenseRenderer>
                  </ContentSelector>
                ) : (
                  <MarkdownSuspenseRenderer {...rest} components={components}>
                    {node}
                  </MarkdownSuspenseRenderer>
                ),
              additionalProps: {
                metadata: metadataNodes,
              },
            });

          const element = render() as unknown as ReactElement;

          return new Proxy(element, {
            get(target, prop, receiver) {
              if (prop === 'value') return node;
              if (prop === Symbol.toPrimitive) return () => node;
              if (prop === 'toString') return () => node;
              if (prop === 'valueOf') return () => node;
              if (typeof prop === 'string' && prop !== 'constructor') {
                const method = (String.prototype as any)[prop];
                if (typeof method === 'function') return method.bind(node);
              }
              if (prop === 'metadata') return metadataNodes;
              if (prop === 'use')
                return (components?: HTMLComponents) => render(components);
              return Reflect.get(target, prop, receiver);
            },
          }) as any;
        },
      };

export type MarkdownCond<T> = T extends {
  nodeType: NodeType | string;
  [NodeTypes.MARKDOWN]: infer M;
  tags?: infer U;
  metadata?: infer V;
}
  ? IntlayerNode<
      M,
      {
        use: (components?: HTMLComponents<'permissive', U>) => ReactNode;
        metadata: DeepTransformContent<V>;
      }
    >
  : never;

export const markdownPlugin: Plugins =
  process.env.INTLAYER_NODE_TYPE_MARKDOWN === 'false'
    ? fallbackPlugin
    : {
        id: 'markdown-plugin',
        canHandle: (node) =>
          typeof node === 'object' && node?.nodeType === NodeTypes.MARKDOWN,
        transform: (node: MarkdownContent, props, deepTransformNode) => {
          const newKeyPath: KeyPath[] = [
            ...props.keyPath,
            {
              type: NodeTypes.MARKDOWN,
            },
          ];

          const children = node[NodeTypes.MARKDOWN];

          return deepTransformNode(children, {
            ...props,
            children,
            keyPath: newKeyPath,
            plugins: [markdownStringPlugin, ...(props.plugins ?? [])],
          });
        },
      };

/** ---------------------------------------------
 *  HTML PLUGIN
 *  --------------------------------------------- */

/**
 * HTML conditional type that enforces:
 * - All components (Standard or Custom) are OPTIONAL in the `use()` method.
 * - Custom components props are strictly inferred from the dictionary definition.
 *
 * This ensures type safety:
 * - `html('<div>Hello <CustomComponent /></div>').use({ CustomComponent: ... })` - optional but typed
 */
export type HTMLPluginCond<T> = T extends {
  nodeType: NodeType | string;
  [NodeTypes.HTML]: infer I;
  tags?: infer U;
}
  ? IntlayerNode<
      I,
      {
        use: (components?: HTMLComponents<'permissive', U>) => ReactNode;
      }
    >
  : never;

const HTMLSuspenseRenderer: FC<Record<string, any>> = (props) => {
  const HTMLRendererPlugin = useLoadDynamic(
    'html-renderer-plugin',
    htmlRendererModulePromise!
  );
  return createElement(HTMLRendererPlugin as any, props);
};

/** HTML plugin. Replaces node with a function that takes components => ReactNode. */
export const htmlPlugin: Plugins =
  process.env.INTLAYER_NODE_TYPE_HTML === 'false'
    ? fallbackPlugin
    : {
        id: 'html-plugin',
        canHandle: (node) =>
          typeof node === 'object' && node?.nodeType === NodeTypes.HTML,

        transform: (node: HTMLContent<string>, props) => {
          const html = node[NodeTypes.HTML];
          const { plugins, ...rest } = props;

          // Type-safe render function that accepts properly typed components
          const render = (userComponents?: HTMLComponents): ReactNode =>
            renderIntlayerNode({
              ...rest,
              value: html,
              children:
                process.env.INTLAYER_EDITOR_ENABLED !== 'false' &&
                editor.enabled ? (
                  <ContentSelector {...rest}>
                    <HTMLSuspenseRenderer
                      {...rest}
                      html={html}
                      userComponents={userComponents}
                    />
                  </ContentSelector>
                ) : (
                  <HTMLSuspenseRenderer
                    {...rest}
                    html={html}
                    userComponents={userComponents}
                  />
                ),
            });

          const element = render() as unknown as ReactElement;

          return new Proxy(element, {
            get(target, prop, receiver) {
              if (prop === 'value') return html;
              if (prop === Symbol.toPrimitive) return () => html;
              if (prop === 'toString') return () => html;
              if (prop === 'valueOf') return () => html;
              if (typeof prop === 'string' && prop !== 'constructor') {
                const method = (String.prototype as any)[prop];
                if (typeof method === 'function') return method.bind(html);
              }
              if (prop === 'use')
                return (userComponents?: HTMLComponents) =>
                  render(userComponents);
              return Reflect.get(target, prop, receiver);
            },
          }) as any;
        },
      };

/** ---------------------------------------------
 *  PLUGINS RESULT
 *  --------------------------------------------- */

export type IInterpreterPluginReact<T, _S, _L extends LocalesValues> = {
  reactNode: ReactNodeCond<T>;
  reactIntlayerNode: IntlayerNodeCond<T>;
  reactInsertion: InsertionCond<T>;
  reactMarkdown: MarkdownCond<T>;
  reactHtml: HTMLPluginCond<T>;
};

/**
 * Insert this type as param of `DeepTransformContent` to avoid `intlayer` package pollution.
 *
 * Otherwise the the `react-intlayer` plugins will override the types of `intlayer` functions.
 */
export type IInterpreterPluginState = Omit<
  IInterpreterPluginStateCore,
  'insertion' // Remove insertion type from core package
> & {
  reactNode: true;
  reactIntlayerNode: true;
  reactMarkdown: true;
  reactHtml: true;
  reactInsertion: true;
};

export type DeepTransformContent<
  T,
  L extends LocalesValues = DeclaredLocales,
> = DeepTransformContentCore<T, IInterpreterPluginState, L>;

const pluginsCache = new Map<string, Plugins[]>();

/**
 * Get the plugins array for React content transformation.
 * This function is used by both getIntlayer and getDictionary to ensure consistent plugin configuration.
 */
export const getPlugins = (
  locale?: LocalesValues,
  fallback: boolean = true
): Plugins[] => {
  const currentLocale = locale ?? internationalization.defaultLocale;
  const cacheKey = `${currentLocale}_${fallback}`;

  if (pluginsCache.has(cacheKey)) {
    return pluginsCache.get(cacheKey)!;
  }

  const plugins = [
    // First: most nodes are plain strings, which every other plugin rejects
    intlayerNodePlugins,
    // Env var allows the bundler to to remove the plugin if not used to make the bundle smaller
    translationPlugin(
      locale ?? internationalization.defaultLocale,
      fallback ? internationalization.defaultLocale : undefined
    ),
    enumerationPlugin,
    pluralPlugin(locale ?? internationalization.defaultLocale),
    conditionPlugin,
    nestedPlugin(locale ?? internationalization.defaultLocale),

    filePlugin,
    genderPlugin,
    selectPlugin,
    // Always include: handle React elements
    reactNodePlugins,
    insertionPlugin,
    markdownPlugin,
    htmlPlugin,
  ] as Plugins[];

  pluginsCache.set(cacheKey, plugins);

  return plugins;
};
