// examples/angular-app/src/app/components/locale-switcher.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { useLocale } from 'angular-intlayer';
import { getLocaleName, getLocalizedUrl, LocalesValues } from 'intlayer';

@Component({
  selector: 'app-locale-switcher',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="locale-switcher">
      <select [ngModel]="locale()" (ngModelChange)="changeLocale($event)">
        <option *ngFor="let loc of availableLocales" [value]="loc">
          {{ getLocaleName(loc) }}
        </option>
      </select>
    </div>
  `,
})
export class LocaleSwitcherComponent {
  private router = inject(Router);

  localeInfo = useLocale({
    onLocaleChange: (newLocale) => {
      const currentPath = this.router.url;
      const localizedPath = getLocalizedUrl(currentPath, newLocale);
      this.router.navigateByUrl(localizedPath);
    },
  });
  locale = this.localeInfo.locale;
  availableLocales = this.localeInfo.availableLocales;

  // Expose getLocaleName to the template
  getLocaleName = getLocaleName;

  changeLocale(newLocale: LocalesValues) {
    this.localeInfo.setLocale(newLocale);
  }
}

// examples/nuxt-app/components/LocaleSwitcher.vue
<template>
  <div class="locale-switcher">
    <select v-model="selectedLocale" @change="changeLocale">
      <option v-for="loc in availableLocales" :key="loc" :value="loc">
        {{ getLocaleName(loc) }}
      </option>
    </select>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { useRouter } from 'vue-router';
import { Locales, getLocaleName, getLocalizedUrl } from 'intlayer';
import { useLocale } from 'vue-intlayer';

// Get Vue Router
const router = useRouter();

// Get locale information and setLocale function
const { locale, availableLocales, setLocale } = useLocale({
  onLocaleChange: (newLocale) => {
    // Get current route and create a localized URL
    const currentPath = router.currentRoute.value.fullPath;
    const localizedPath = getLocalizedUrl(currentPath, newLocale);

    // Navigate to the localized route without reloading the page
    router.push(localizedPath);
  },
});

// Track the selected locale with a ref
const selectedLocale = ref(locale.value);

// Update the locale when the selection changes
const changeLocale = () => setLocale(selectedLocale.value);

// Keep the selectedLocale in sync with the global locale
watch(
  () => locale.value,
  (newLocale) => {
    selectedLocale.value = newLocale;
  }
);
</script>
