// packages/solid-intlayer/src/client/useRewriteURL.ts
import configuration from '@intlayer/config/built';
import { getRewritePath } from '@intlayer/core/localization';
import type { Locale } from '@intlayer/types/allLocales';
import { createEffect } from 'solid-js';
import { useLocale } from './useLocale';

/**
 * Client-side hook to manage URL rewrites in Solid without triggering a router navigation.
 * It uses `window.history.replaceState` to update the URL in the address bar.
 */
export const useRewriteURL = (): void => {
  const { locale } = useLocale();
  const rewrite = configuration?.routing?.rewrite;

  createEffect(() => {
    if (typeof window === 'undefined' || !rewrite) return;

    const loc = locale();
    const pathname = window.location.pathname;
    const targetPath = getRewritePath(pathname, loc as Locale, rewrite);

    if (targetPath && targetPath !== pathname) {
      window.history.replaceState(
        window.history.state,
        '',
        targetPath + window.location.search + window.location.hash
      );
    }
  });
};

// packages/lit-intlayer/src/client/useRewriteURL.ts
import configuration from '@intlayer/config/built';
import { getRewritePath } from '@intlayer/core/localization';
import type { Locale } from '@intlayer/types/allLocales';
import type { ReactiveController, ReactiveControllerHost } from 'lit';
import { getIntlayerClient } from './installIntlayer';

/**
 * ReactiveController that keeps the browser URL in sync with the current locale.
 *
 * Uses `window.history.replaceState` to update the address bar without
 * triggering a full navigation.
 *
 * @example
 * ```ts
 * class AppShell extends LitElement {
 *   private _rewrite = useRewriteURL(this);
 * }
 * ```
 */
class RewriteURLController implements ReactiveController {
  private readonly host: ReactiveControllerHost;
  private _unsubscribe: (() => void) | null = null;

  constructor(host: ReactiveControllerHost) {
    this.host = host;
    host.addController(this);
  }

  private _rewrite(locale: string): void {
    const rewrite = configuration?.routing?.rewrite;
    if (typeof window === 'undefined' || !rewrite) return;

    const pathname = window.location.pathname;
    const targetPath = getRewritePath(pathname, locale as Locale, rewrite);

    if (targetPath && targetPath !== pathname) {
      window.history.replaceState(
        window.history.state,
        '',
        targetPath + window.location.search + window.location.hash
      );
    }
  }

  hostConnected(): void {
    const client = getIntlayerClient();

    // Rewrite on initial connect
    this._rewrite(client.locale);

    this._unsubscribe = client.subscribe((newLocale) => {
      this._rewrite(newLocale);
    });
  }

  hostDisconnected(): void {
    this._unsubscribe?.();
    this._unsubscribe = null;
  }
}

export const useRewriteURL = (host: ReactiveControllerHost): void => {
  new RewriteURLController(host);
};
