// examples/vite-app/src/App.tsx
import { FC, useState } from 'react';
import { IntlayerProvider, useIntlayer } from 'react-intlayer';
import reactLogo from './assets/react.svg';
import viteLogo from '/vite.svg';
import './App.css';
import { LocaleSwitcher } from './components/LangSwitcherDropDown';

const AppContent: FC = () => {
  const [count, setCount] = useState(0);
  const content = useIntlayer('app');

  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt={content.viteLogo.value} />
        </a>
        <a href="https://react.dev" target="_blank">
          <img
            src={reactLogo}
            className="logo react"
            alt={content.reactLogo.value}
          />
        </a>
      </div>
      <h1>{content.title}</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          {content.count}
          {count}
        </button>
        <p>{content.edit}</p>
      </div>
      <p className="read-the-docs">{content.readTheDocs}</p>
      <div className="absolute bottom-5 right-5 z-50">
        <LocaleSwitcher />
      </div>
    </>
  );
};

function App() {
  return (
    <IntlayerProvider>
      <AppContent />
    </IntlayerProvider>
  );
}

export default App;

// examples/vite-solid-app/src/App.tsx
import {
  IntlayerProvider,
  MarkdownProvider,
  useIntlayer,
} from 'solid-intlayer';
import { createSignal } from 'solid-js';
import './App.css';
import solidLogo from './assets/solid.svg';
import viteLogo from '/vite.svg';

const AppContent = () => {
  const [count, setCount] = createSignal(0);
  const content = useIntlayer('app');
  const {
    viteAndVue,
    viteLogoLabel,
    solidLogoLabel,
    countIs,
    editSrcAppTsx,
    readTheDocs,
  } = content();

  return (
    <>
      <div>
        <a href="https://vite.dev" target="_blank">
          <img src={viteLogo} class="logo" alt={viteLogoLabel.value} />
        </a>
        <a href="https://solidjs.com" target="_blank">
          <img src={solidLogo} class="logo solid" alt={solidLogoLabel.value} />
        </a>
      </div>
      <h1>{viteAndVue}</h1>
      <div class="card">
        <button onClick={() => setCount((count) => count + 1)}>
          {/* {countIs({ count: count() })} */}
        </button>
        {/* <p>{editSrcAppTsx}</p> */}
      </div>
      {/* <p class="read-the-docs">{readTheDocs}</p> */}
    </>
  );
};

export const App = () => (
  <IntlayerProvider>
    <MarkdownProvider renderMarkdown={(content) => <div>{content}</div>}>
      <AppContent />
    </MarkdownProvider>
  </IntlayerProvider>
);
