// examples/vite-svelte-app/src/App.svelte
<script lang="ts">
import { useIntlayer } from 'svelte-intlayer';
import {
  useCompact,
  useCurrency,
  useDate,
  useList,
  useNumber,
  usePercentage,
  useRelativeTime,
  useUnit,
} from 'svelte-intlayer/format';
import { MarkdownProvider } from 'svelte-intlayer/markdown';
import svelteLogo from './assets/svelte.svg';
import QualifiedContentDemo from './components/QualifiedContentDemo/index.svelte';
import LocaleSwitcher from './lib/LocaleSwitcher.svelte';

let count = $state(0);
const app = useIntlayer('app');
const bm = useIntlayer('benchmark');

const number = useNumber();
const percentage = usePercentage();
const currency = useCurrency();
const date = useDate();
const relativeTime = useRelativeTime();
const unit = useUnit();
const compact = useCompact();
const list = useList();

const now = new Date();
const in3Days = new Date(now.getTime() + 3 * 864e5);

type Row = { id: number; name: string; desc: string; result: unknown };
type Section = { label: string; rows: Row[] };

const getSections = (): Section[] => {
  let id = 0;
  const r = (name: string, desc: string, result: unknown): Row => ({
    id: ++id,
    name,
    desc,
    result,
  });
  return [
    {
      label: 'Content Nodes',
      rows: [
        r('t()', 'Simple translation', $bm.n01_t),
        r('enu() −2', "count=-2 → '<-1'", $bm.n02_enu(-2)),
        r('enu() 0', "count=0 → '0'", $bm.n02_enu(0)),
        r('enu() 1', "count=1 → '1'", $bm.n02_enu(1)),
        r('enu() 7', "count=7 → '>5'", $bm.n02_enu(7)),
        r('enu() 25', "count=25 → '>19'", $bm.n02_enu(25)),
        r('cond() true', 'condition=true', $bm.n03_cond(true)),
        r('cond() false', 'condition=false', $bm.n03_cond(false)),
        r("gender() 'male'", "gender='male'", $bm.n04_gender('male')),
        r("gender() 'female'", "gender='female'", $bm.n04_gender('female')),
        r(
          'insert()',
          "{name:'Alice', age:30}",
          $bm.n05_insert({ name: 'Alice', age: 30 })
        ),
        r('md()', 'Markdown string', 'md' as const),
        r('html()', 'HTML string', 'html' as const),
        r('plural() 1', "count=1 → 'one'", $bm.n22_plural(1)),
        r('plural() 5', "count=5 → 'other'", $bm.n22_plural(5)),
      ],
    },
    {
      label: 'Combinations',
      rows: [
        r(
          'insert(t())',
          "{name:'Alice', place:'Paris'}",
          $bm.n08_insert_t({ name: 'Alice', place: 'Paris' })
        ),
        r('t(md())', 'Translation of markdown', 'n09_t_of_md' as const),
        r('md(t())', 'Markdown from translation', 'n10_md_t' as const),
        r('enu(t()) 2', 'count=2', $bm.n11_enu_t(2)),
        r(
          'insert(enu(t()))',
          '{count:3,name:"Alice"}(3)',
          $bm.n12_insert_enu_t({ count: 3, name: 'Alice' })(3)
        ),
        r('cond(t()) true', 'true', $bm.n13_cond_t(true)),
        r(
          'cond(insert(t()))',
          "true · {name:'Alice'}",
          $bm.n14_cond_insert_t(true)?.({ name: 'Alice' })
        ),
        r(
          'gender(insert(t()))',
          "female · {name:'Alice'}",
          $bm.n15_gender_insert_t('female')?.({ name: 'Alice' })
        ),
        r(
          'plural(html()) 1',
          "count=1 → '<b>1</b> day'",
          'n23_plural_html_1' as const
        ),
        r(
          'plural(html()) 5',
          "count=5 → '<b>5</b> days'",
          'n23_plural_html_5' as const
        ),
        r(
          'insert(html())',
          "{name:'Alice'} → 'Hello <b>Alice</b>'",
          'n24_insert_html' as const
        ),
        r(
          'plural(md()) 1',
          "count=1 → '**1** day'",
          'n25_plural_md_1' as const
        ),
        r(
          'plural(md()) 5',
          "count=5 → '**5** days'",
          'n25_plural_md_5' as const
        ),
        r(
          'insert(md())',
          "{name:'Alice'} → 'Hello **Alice**'",
          'n26_insert_md' as const
        ),
      ],
    },
    {
      label: 'Data Structures',
      rows: [
        r(
          'nested object',
          'obj.level1.level2',
          $bm.n17_nested_object.level1.level2
        ),
        r(
          "array ['string']",
          "['item1','item2','item3']",
          ($bm.n18_array_strings as string[]).join(', ')
        ),
        r('array [t()]', 'Array of translations', $bm.n19_array_translations),
        r(
          'array [{obj}]',
          'Array of {name,role}',
          $bm.n20_array_objects.map((o) => `${o.name} (${o.role})`).join(' · ')
        ),
        r("nest('app','title')", 'Cross-dict reference', $bm.n21_nest),
      ],
    },
    {
      label: 'Formatters',
      rows: [
        r('useNumber()', '123456.789', $number(123456.789)),
        r('usePercentage()', '0.25', $percentage(0.25)),
        r(
          'useCurrency()',
          '1234.5, EUR',
          $currency(1234.5, { currency: 'EUR' })
        ),
        r('useDate()', 'now, short', $date(now, 'short')),
        r(
          'useRelativeTime()',
          'now → +3 days',
          $relativeTime(now, in3Days, { unit: 'day' })
        ),
        r(
          'useUnit()',
          '5, kilometer, long',
          $unit(5, { unit: 'kilometer', unitDisplay: 'long' })
        ),
        r('useCompact()', '1200', $compact(1200)),
        r(
          'useList()',
          "['apple','banana','orange']",
          $list(['apple', 'banana', 'orange'])
        ),
      ],
    },
  ];
};

let sections = $derived(getSections());
</script>

<MarkdownProvider>
  <main>
    <div class="locale-switcher-container">
      <LocaleSwitcher />
    </div>

    <div>
      <a href="https://vitejs.dev" target="_blank" rel="noopener">
        <img src="/vite.svg" class="logo" alt={$app.viteLogoLabel} />
      </a>
      <a href="https://svelte.dev" target="_blank" rel="noopener">
        <img src={svelteLogo} class="logo svelte" alt={$app.svelteLogoLabel} />
      </a>
    </div>

    <h1>{$app.title}</h1>

    <div class="card">
      <button onclick={() => count++}>
        {$app.countIs({ count })}
      </button>
    </div>

    <div class="benchmark-wrap">
      <h2 class="benchmark-title">Intlayer Node Benchmark</h2>
      <div class="table-scroll">
        <table class="benchmark-table">
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Description</th>
              <th>Result</th>
            </tr>
          </thead>
          <tbody>
            {#each sections as section}
              <tr class="section-header">
                <td colspan="4">{section.label}</td>
              </tr>
              {#each section.rows as row}
                <tr class:even={row.id % 2 === 0}>
                  <td class="col-id">{row.id}</td>
                  <td class="col-name"><code>{row.name}</code></td>
                  <td class="col-desc">{row.desc}</td>
                  <td class="col-result">
                    {#if row.result === 'md'}
                      {@const Comp = $bm.n06_md}
                      <div class="md-preview"><Comp /></div>
                    {:else if row.result === 'html'}
                      {@html String($bm.n07_html)}
                    {:else if row.result === 'n09_t_of_md'}
                      {@const Comp = $bm.n09_t_of_md}
                      <div class="md-preview"><Comp /></div>
                    {:else if row.result === 'n10_md_t'}
                      {@const Comp = $bm.n10_md_t}
                      <div class="md-preview"><Comp /></div>
                    {:else if row.result === 'n23_plural_html_1'}
                      {@html String($bm.n23_plural_html(1))}
                    {:else if row.result === 'n23_plural_html_5'}
                      {@html String($bm.n23_plural_html(5))}
                    {:else if row.result === 'n24_insert_html'}
                      {@html String($bm.n24_insert_html({ name: 'Alice' }))}
                    {:else if row.result === 'n25_plural_md_1'}
                      {@const Comp = $bm.n25_plural_md(1)}
                      <div class="md-preview"><Comp /></div>
                    {:else if row.result === 'n25_plural_md_5'}
                      {@const Comp = $bm.n25_plural_md(5)}
                      <div class="md-preview"><Comp /></div>
                    {:else if row.result === 'n26_insert_md'}
                      {@const Comp = $bm.n26_insert_md({ name: 'Alice' })}
                      <div class="md-preview"><Comp /></div>
                    {:else}
                      {row.result}
                    {/if}
                  </td>
                </tr>
              {/each}
            {/each}
          </tbody>
        </table>
      </div>
    </div>

    <QualifiedContentDemo />

    <p class="read-the-docs">{$app.readTheDocs}</p>
  </main>
</MarkdownProvider>

<style>
  main {
    max-width: 1100px;
    margin: 0 auto;
    padding: 2rem;
    text-align: center;
    position: relative;
  }
  .locale-switcher-container {
    position: absolute;
    top: 1em;
    right: 1em;
  }
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover { filter: drop-shadow(0 0 2em #646cffaa); }
  .logo.svelte:hover { filter: drop-shadow(0 0 2em #ff3e00aa); }

  .benchmark-wrap { margin: 1.5rem 0; text-align: left; }
  .benchmark-title { font-size: 1.25rem; color: #ff3e00; margin-bottom: 1rem; }
  .table-scroll { overflow-x: auto; }

  .benchmark-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.88em;
  }
  .benchmark-table th {
    padding: 8px 14px;
    background: rgba(255, 62, 0, 0.15);
    border-bottom: 2px solid rgba(255, 62, 0, 0.4);
    text-align: left;
    font-weight: 600;
    white-space: nowrap;
  }
  .benchmark-table td {
    padding: 6px 14px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.07);
    vertical-align: top;
  }
  .benchmark-table tr.even td { background: rgba(255, 255, 255, 0.025); }

  .section-header td {
    padding: 6px 14px;
    background: rgba(255, 62, 0, 0.07);
    font-weight: 700;
    font-size: 0.75em;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    color: #888;
  }

  .col-id { width: 36px; color: #666; font-family: monospace; }
  .col-name { width: 200px; }
  .col-name code {
    background: rgba(255, 62, 0, 0.12);
    padding: 2px 7px;
    border-radius: 4px;
    font-size: 0.85em;
  }
  .col-desc { width: 280px; color: #aaa; font-family: monospace; font-size: 0.83em; }
  .col-result { max-width: 360px; }
  .md-preview { font-size: 0.82em; line-height: 1.4; }

  .read-the-docs { color: #888; margin-top: 2rem; }
  .card { margin: 1rem 0; }
</style>

// examples/vite-solid-app/src/App.tsx
import { A, Route, useLocation, useNavigate } from '@solidjs/router';
import { getLocalizedUrl, localeMap } from 'intlayer';
import { IntlayerProvider, useIntlayer, useLocale } from 'solid-intlayer';
import {
  useCompact,
  useCurrency,
  useDate,
  useList,
  useNumber,
  usePercentage,
  useRelativeTime,
  useUnit,
} from 'solid-intlayer/format';
import { MarkdownProvider } from 'solid-intlayer/markdown';
import { createSignal, For, type JSX, type ParentComponent } from 'solid-js';
import './App.css';

import viteLogo from '/vite.svg';
import solidLogo from './assets/solid.svg';

const LocaleSwitcher = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const { locale, setLocale, availableLocales } = useLocale({
    onLocaleChange: (loc) => {
      const pathWithLocale = getLocalizedUrl(location.pathname, loc);
      navigate(pathWithLocale);
    },
  });

  return (
    <select
      value={locale()}
      onChange={(e) => setLocale(e.currentTarget.value)}
      class="locale-switcher"
    >
      <For each={availableLocales}>
        {(loc) => (
          <option value={loc} selected={loc === locale()}>
            {loc}
          </option>
        )}
      </For>
    </select>
  );
};

const Layout: ParentComponent = (props) => {
  const { locale } = useLocale();

  return (
    <>
      <nav>
        <A href={getLocalizedUrl('/', locale())} end activeClass="active">
          Home
        </A>
        <LocaleSwitcher />
      </nav>
      {props.children}
    </>
  );
};

// ─── Styles ──────────────────────────────────────────────────────────────────

const th: Record<string, string> = {
  padding: '8px 14px',
  'text-align': 'left',
  'font-weight': '600',
  background: 'rgba(79,136,198,0.18)',
  'border-bottom': '2px solid rgba(79,136,198,0.4)',
  'white-space': 'nowrap',
};
const tdBase: Record<string, string> = {
  padding: '6px 14px',
  'border-bottom': '1px solid rgba(255,255,255,0.07)',
  'vertical-align': 'top',
};
const sectionHdr: Record<string, string> = {
  padding: '6px 14px',
  background: 'rgba(79,136,198,0.08)',
  'font-weight': '700',
  'font-size': '0.75em',
  'letter-spacing': '0.08em',
  'text-transform': 'uppercase',
  color: '#888',
};

// ─── Benchmark ───────────────────────────────────────────────────────────────

const BenchmarkTable = () => {
  const content = useIntlayer('benchmark');

  const number = useNumber();
  const percentage = usePercentage();
  const currency = useCurrency();
  const date = useDate();
  const relativeTime = useRelativeTime();
  const unit = useUnit();
  const compact = useCompact();
  const list = useList();

  const now = new Date();
  const in3Days = new Date(now.getTime() + 3 * 864e5);

  type Row = { name: string; desc: string; result: () => JSX.Element };
  type Section = { label: string; rows: Row[] };

  const sections: Section[] = [
    {
      label: 'Content Nodes',
      rows: [
        {
          name: 't()',
          desc: 'Simple translation',
          result: () => content().n01_t,
        },
        {
          name: 't().value',
          desc: 'Raw string value',
          result: () => content().n01_t.value,
        },
        {
          name: 'enu() −2',
          desc: "count=-2 → '<-1'",
          result: () => content().n02_enu(-2),
        },
        {
          name: 'enu() 0',
          desc: "count=0 → '0'",
          result: () => content().n02_enu(0),
        },
        {
          name: 'enu() 1',
          desc: "count=1 → '1'",
          result: () => content().n02_enu(1),
        },
        {
          name: 'enu() 7',
          desc: "count=7 → '>5'",
          result: () => content().n02_enu(7),
        },
        {
          name: 'enu() 25',
          desc: "count=25 → '>19'",
          result: () => content().n02_enu(25),
        },
        {
          name: 'cond() true',
          desc: 'condition=true',
          result: () => content().n03_cond(true),
        },
        {
          name: 'cond() false',
          desc: 'condition=false',
          result: () => content().n03_cond(false),
        },
        {
          name: "gender() 'male'",
          desc: "gender='male'",
          result: () => content().n04_gender('male'),
        },
        {
          name: "gender() 'female'",
          desc: "gender='female'",
          result: () => content().n04_gender('female'),
        },
        {
          name: 'insert()',
          desc: "{name:'Alice', age:30}",
          result: () => content().n05_insert({ name: 'Alice', age: 30 }),
        },
        {
          name: 'md()',
          desc: 'Markdown string',
          result: () => content().n06_md,
        },
        {
          name: 'html()',
          desc: 'HTML string',
          result: () => content().n07_html.use({}),
        },
      ],
    },
    {
      label: 'Combinations',
      rows: [
        {
          name: 'insert(t())',
          desc: "{name:'Alice', place:'Paris'}",
          result: () =>
            content().n08_insert_t({ name: 'Alice', place: 'Paris' }),
        },
        {
          name: 't(md())',
          desc: 'Translation of markdown',
          result: () => content().n09_t_of_md,
        },
        {
          name: 'md(t())',
          desc: 'Markdown from translation',
          result: () => content().n10_md_t,
        },
        {
          name: 'enu(t()) 2',
          desc: 'count=2',
          result: () => content().n11_enu_t(2),
        },
        {
          name: 'insert(enu(t()))',
          desc: '{count:3,name:"Alice"}(3)',
          result: () =>
            content().n12_insert_enu_t({ count: 3, name: 'Alice' })(3),
        },
        {
          name: 'cond(t()) true',
          desc: 'true',
          result: () => content().n13_cond_t(true),
        },
        {
          name: 'cond(insert(t()))',
          desc: "true · {name:'Alice'}",
          result: () => content().n14_cond_insert_t(true)?.({ name: 'Alice' }),
        },
        {
          name: 'gender(insert(t()))',
          desc: "female · {name:'Alice'}",
          result: () =>
            content().n15_gender_insert_t('female')?.({ name: 'Alice' }),
        },
      ],
    },
    {
      label: 'Data Structures',
      rows: [
        {
          name: 'nested object',
          desc: 'obj.level1.level2',
          result: () => content().n17_nested_object.level1.level2,
        },
        {
          name: "array ['string']",
          desc: "['item1','item2','item3']",
          result: () => content().n18_array_strings,
        },
        {
          name: 'array [t()]',
          desc: 'Array of translations',
          result: () => content().n19_array_translations,
        },
        {
          name: 'array [{obj}]',
          desc: 'Array of {name,role}',
          result: () =>
            content()
              .n20_array_objects.map((o) => `${o.name} (${o.role})`)
              .join(' · '),
        },
        {
          name: "nest('app','title')",
          desc: 'Cross-dict reference',
          result: () => content().n21_nest,
        },
      ],
    },
    {
      label: 'Formatters',
      rows: [
        {
          name: 'useNumber()',
          desc: '123456.789',
          result: () => number(123456.789),
        },
        {
          name: 'usePercentage()',
          desc: '0.25',
          result: () => percentage(0.25),
        },
        {
          name: 'useCurrency()',
          desc: '1234.5, EUR',
          result: () => currency(1234.5, { currency: 'EUR' }),
        },
        {
          name: 'useDate()',
          desc: 'now, short',
          result: () => date(now, 'short'),
        },
        {
          name: 'useRelativeTime()',
          desc: 'now → +3 days',
          result: () => relativeTime(now, in3Days, { unit: 'day' }),
        },
        {
          name: 'useUnit()',
          desc: '5, kilometer, long',
          result: () => unit(5, { unit: 'kilometer', unitDisplay: 'long' }),
        },
        { name: 'useCompact()', desc: '1200', result: () => compact(1200) },
        {
          name: 'useList()',
          desc: "['apple','banana','orange']",
          result: () => list(['apple', 'banana', 'orange']),
        },
      ],
    },
  ];

  let rowIndex = 0;

  return (
    <div style={{ margin: '24px 0', 'overflow-x': 'auto' }}>
      <h2
        style={{
          'margin-bottom': '16px',
          'font-size': '1.25em',
          color: '#4f88c6',
        }}
      >
        Intlayer Node Benchmark
      </h2>
      <table
        style={{
          width: '100%',
          'border-collapse': 'collapse',
          'font-size': '0.88em',
          'text-align': 'left',
        }}
      >
        <thead>
          <tr>
            <th style={th}>#</th>
            <th style={th}>Name</th>
            <th style={th}>Description</th>
            <th style={th}>Result</th>
          </tr>
        </thead>
        <tbody>
          <For each={sections}>
            {(section) => (
              <>
                <tr>
                  <td colspan="4" style={sectionHdr}>
                    {section.label}
                  </td>
                </tr>
                <For each={section.rows}>
                  {(row) => {
                    const id = ++rowIndex;
                    return (
                      <tr
                        style={{
                          background:
                            id % 2 === 0
                              ? 'rgba(255,255,255,0.025)'
                              : 'transparent',
                        }}
                      >
                        <td
                          style={{
                            ...tdBase,
                            color: '#666',
                            'font-family': 'monospace',
                          }}
                        >
                          {id}
                        </td>
                        <td style={tdBase}>
                          <code
                            style={{
                              background: 'rgba(79,136,198,0.12)',
                              padding: '2px 7px',
                              'border-radius': '4px',
                              'font-size': '0.85em',
                            }}
                          >
                            {row.name}
                          </code>
                        </td>
                        <td
                          style={{
                            ...tdBase,
                            color: '#aaa',
                            'font-family': 'monospace',
                            'font-size': '0.83em',
                          }}
                        >
                          {row.desc}
                        </td>
                        <td style={tdBase}>{row.result()}</td>
                      </tr>
                    );
                  }}
                </For>
              </>
            )}
          </For>
        </tbody>
      </table>
    </div>
  );
};

// ─── Home ────────────────────────────────────────────────────────────────────

const Home = () => {
  const [count, setCount] = createSignal(0);
  const content = useIntlayer('app');

  return (
    <>
      <div>
        <a href="https://vite.dev" target="_blank" rel="noopener">
          <img
            src={viteLogo}
            class="logo"
            alt={content().viteLogoLabel.value}
          />
        </a>
        <a href="https://solidjs.com" target="_blank" rel="noopener">
          <img
            src={solidLogo}
            class="logo solid"
            alt={content().solidLogoLabel.value}
          />
        </a>
      </div>

      <h1>{content().title}</h1>

      <div class="card">
        <button type="button" onClick={() => setCount((c) => c + 1)}>
          {content().countIs({ count: count() })}
        </button>
      </div>

      <BenchmarkTable />

      <p class="read-the-docs">{content().readTheDocs}</p>
    </>
  );
};

// ─── App ─────────────────────────────────────────────────────────────────────

export const App = () =>
  localeMap(({ locale, urlPrefix }) => (
    <Route
      path={urlPrefix}
      component={(props) => (
        <IntlayerProvider locale={locale}>
          <MarkdownProvider
            renderMarkdown={async (md) => {
              const { compileMarkdown } = await import(
                'solid-intlayer/markdown'
              );
              return compileMarkdown(md);
            }}
          >
            <Layout>{props.children}</Layout>
          </MarkdownProvider>
        </IntlayerProvider>
      )}
    >
      <Route path="/" component={Home} />
    </Route>
  ));
