// examples/vite-svelte-app/src/lib/LocaleSwitcher.svelte
<script lang="ts">
import { getLocaleName } from 'intlayer';
import { useLocale } from 'svelte-intlayer';

// Get locale information and setLocale function
const { locale, availableLocales, setLocale } = useLocale();

// Handle locale change
const changeLocale = (event: Event) => {
  const target = event.target as HTMLSelectElement;
  const newLocale = target.value;
  setLocale(newLocale);
};
</script>

<div class="locale-switcher">
  <select value={$locale} on:change={changeLocale}>
    {#each availableLocales ?? [] as loc}
      <option value={loc}>
        {getLocaleName(loc)}
      </option>
    {/each}
  </select>
</div>

<style>
  .locale-switcher {
    display: inline-block;
  }

  select {
    padding: 0.5em 1em;
    border: 1px solid #646cff;
    border-radius: 8px;
    background-color: #1a1a1a;
    color: rgba(255, 255, 255, 0.87);
    font-family: inherit;
    font-size: 1em;
    cursor: pointer;
    transition: border-color 0.25s;
  }

  select:hover {
    border-color: #747bff;
  }

  select:focus {
    outline: 4px auto -webkit-focus-ring-color;
  }
</style>

// examples/vite-lit-app/src/locale-switcher.ts
import { getLocaleName } from 'intlayer';
import { css, html, LitElement } from 'lit';
import { customElement } from 'lit/decorators.js';
import { useLocale } from 'lit-intlayer';

/**
 * `<locale-switcher>` — dropdown to switch the application locale.
 *
 * Uses `useLocale` ReactiveController so the element re-renders whenever
 * the locale changes anywhere in the app.
 */
@customElement('locale-switcher')
export class LocaleSwitcher extends LitElement {
  private locale = useLocale(this);

  private _onChange(e: Event) {
    const select = e.target as HTMLSelectElement;
    this.locale.setLocale(select.value as any);
  }

  override render() {
    return html`
      <select
        aria-label="Language"
        @change=${this._onChange}
      >
        ${this.locale.availableLocales.map(
          (loc) => html`
            <option value=${loc} ?selected=${loc === this.locale.locale}>
              ${getLocaleName(loc)}
            </option>
          `
        )}
      </select>
    `;
  }

  static override styles = css`
    :host {
      display: inline-block;
    }

    select {
      font: inherit;
      font-size: 14px;
      padding: 4px 8px;
      border-radius: 6px;
      border: 1px solid var(--border, #e5e4e7);
      background: transparent;
      color: inherit;
      cursor: pointer;
    }
  `;
}

declare global {
  interface HTMLElementTagNameMap {
    'locale-switcher': LocaleSwitcher;
  }
}
