// packages/angular-intlayer/src/editor/useCrossFrameMessageListener.ts
import { DestroyRef, inject } from '@angular/core';
import type { MessageKey } from '@intlayer/editor';
import { getEditorStateManager } from './installIntlayerEditor';

export const useCrossFrameMessageListener = <S>(
  key: `${MessageKey}` | `${MessageKey}/post` | `${MessageKey}/get`,
  onEventTriggered?: (data: S) => void
) => {
  const manager = getEditorStateManager();

  if (onEventTriggered && manager) {
    const unsub = manager.messenger.subscribe(
      key,
      onEventTriggered as (data: unknown) => void
    );

    try {
      const destroyRef = inject(DestroyRef, { optional: true });
      destroyRef?.onDestroy(unsub);
    } catch {}
  }

  return (data?: S) => manager?.messenger.send(key, data);
};

// packages/solid-intlayer/src/editor/contexts/useCrossFrameMessageListener.tsx
import type { MessageKey } from '@intlayer/editor';
import { onCleanup } from 'solid-js';
import { useEditorStateManager } from './EditorProvider';

export const useCrossFrameMessageListener = <S,>(
  key: `${MessageKey}` | `${MessageKey}/post` | `${MessageKey}/get`,
  onEventTriggered?: (data: S) => void
) => {
  const manager = useEditorStateManager();

  if (onEventTriggered) {
    const unsub = manager.messenger.subscribe(
      key,
      onEventTriggered as (data: unknown) => void
    );
    onCleanup(unsub);
  }

  return (data?: S) => manager.messenger.send(key, data);
};
