// packages/@intlayer/editor-react/src/useIframeClickInterceptor.tsx
'use client';

import { MessageKey, mergeIframeClick } from '@intlayer/editor';
import { useCrossFrameMessageListener } from './useCrossFrameMessageListener';

/**
 * Broadcasts mousedown events from within an iframe to the parent frame.
 * Called in the client application (inside the iframe).
 * Note: EditorStateManager.start() already sets this up in client mode.
 * This hook exists for explicit / standalone use cases.
 */
export const useIframeClickInterceptor = () => {
  useCrossFrameMessageListener<undefined>(MessageKey.INTLAYER_IFRAME_CLICKED);
};

/**
 * Merges received iframe click events into the parent's DOM event stream.
 * Called in the editor (parent frame).
 */
export const useIframeClickMerger = () => {
  useCrossFrameMessageListener<MessageEvent>(
    MessageKey.INTLAYER_IFRAME_CLICKED,
    mergeIframeClick
  );
};

// packages/solid-intlayer/src/editor/contexts/useIframeClickInterceptor.tsx
'use client';

import { MessageKey, mergeIframeClick } from '@intlayer/editor';
import { onCleanup, onMount } from 'solid-js';
import { useCrossFrameMessageListener } from './useCrossFrameMessageListener';

/**
 * Custom hook that intercepts clicks on the page and sends them via `postMessage`.
 *
 * This is useful in iframe contexts where you want the parent frame to know
 * about click events happening within the iframe.
 */
export const useIframeClickInterceptor = () => {
  const postClickEvent = useCrossFrameMessageListener<undefined>(
    MessageKey.INTLAYER_IFRAME_CLICKED
  );

  onMount(() => {
    const handleClick = (event: MouseEvent) => {
      // Send click event to the parent frame
      postClickEvent();
    };

    // Add click event listener to the document
    document.addEventListener('mousedown', handleClick);

    // Cleanup function to remove the event listener
    onCleanup(() => {
      document.removeEventListener('mousedown', handleClick);
    });
  });
};

export const useIframeClickMerger = () =>
  useCrossFrameMessageListener<MessageEvent>(
    MessageKey.INTLAYER_IFRAME_CLICKED,
    mergeIframeClick
  );
