// packages/angular-intlayer/src/UI/ContentSelector.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  computed,
  type ElementRef,
  EventEmitter,
  HostListener,
  Input,
  type OnDestroy,
  type OnInit,
  Output,
  signal,
  ViewChild,
} from '@angular/core';

const DEFAULT_PRESS_DETECT_DURATION = 250;

@Component({
  selector: 'app-content-selector',
  template: `
    <span
      #containerRef
      role="button"
      tabindex="0"
      (click)="handleClick($event)"
      (mousedown)="handleMouseDown()"
      (mouseup)="handleMouseUp()"
      (mouseleave)="handleMouseUp()"
      (touchstart)="handleMouseDown()"
      (touchend)="handleMouseUp()"
      (touchcancel)="handleMouseUp()"
      (blur)="handleBlur()"
      (mouseenter)="onMouseEnter()"
      [ngStyle]="getContainerStyle()"
    >
      <ng-content></ng-content>
    </span>
  `,
  standalone: true,
  imports: [CommonModule],
})
export class ContentSelectorComponent implements OnInit, OnDestroy {
  @Input() onClickOutside?: () => void;
  @Input() pressDuration?: number;
  @Input() isSelecting?: boolean;

  @Output() click = new EventEmitter<MouseEvent>();
  @Output() press = new EventEmitter<void>();

  @ViewChild('containerRef', { static: true })
  containerRef!: ElementRef<HTMLSpanElement>;

  private isHovered = signal(false);
  private isSelectingState = signal(false);
  private pressTimerRef: ReturnType<typeof setTimeout> | null = null;

  private readonly isSelectingComputed = computed(
    () => this.isSelecting ?? this.isSelectingState()
  );

  private readonly isStringSlot = computed(() => {
    // In Angular, we can't easily detect if content is just text
    // This would need to be determined differently or simplified
    return true; // Simplified for now
  });

  ngOnInit(): void {
    this.isSelectingState.set(this.isSelecting ?? false);
  }

  ngOnDestroy(): void {
    this.clearPressTimer();
  }

  @HostListener('document:mousedown', ['$event'])
  onDocumentMouseDown(event: MouseEvent): void {
    this.handleClickOutside(event);
  }

  private handleOnLongPress(): void {
    this.isSelectingState.set(true);
    this.press.emit();
  }

  private startPressTimer(): void {
    this.pressTimerRef = setTimeout(() => {
      this.handleOnLongPress();
    }, this.pressDuration ?? DEFAULT_PRESS_DETECT_DURATION);
  }

  private clearPressTimer(): void {
    if (this.pressTimerRef) {
      clearTimeout(this.pressTimerRef);
      this.pressTimerRef = null;
    }
  }

  handleMouseDown(): void {
    this.clearPressTimer();
    this.startPressTimer();
  }

  handleMouseUp(): void {
    this.isHovered.set(false);
    this.clearPressTimer();
  }

  private handleClickOutside(event: MouseEvent): void {
    if (
      this.containerRef?.nativeElement &&
      !this.containerRef.nativeElement.contains(event.target as Node)
    ) {
      this.isSelectingState.set(false);
      this.onClickOutside?.();
    }
  }

  handleClick(e: MouseEvent): void {
    if (this.isSelectingComputed()) {
      e.preventDefault();
      e.stopPropagation();
    }
    this.click.emit(e);
  }

  handleBlur(): void {
    this.isSelectingState.set(false);
  }

  onMouseEnter(): void {
    this.isHovered.set(true);
  }

  getContainerStyle(): { [key: string]: any } {
    return {
      display: this.isStringSlot() ? 'inline' : 'inline-block',
      cursor: 'pointer',
      userSelect: 'none',
      borderRadius: '0.375rem',
      outlineWidth: '2px',
      outlineOffset: '4px',
      outlineStyle: 'solid',
      outlineColor:
        this.isSelectingComputed() || this.isHovered()
          ? 'inherit'
          : 'transparent',
      transition: 'all 100ms 50ms ease-in-out',
    };
  }
}

// packages/vue-intlayer/src/UI/ContentSelector.vue
<script setup lang="ts">
import { ref, computed, useSlots, onMounted, onBeforeUnmount } from 'vue';
type Props = {
  onClickOutside?: () => void;
  pressDuration?: number;
  isSelecting?: boolean;
};

const DEFAULT_PRESS_DETECT_DURATION = 250;

const props = defineProps<Props>();
const emit = defineEmits(['click', 'press']);

const containerRef = ref<HTMLElement | null>(null);
const isHovered = ref(false);
const isSelectingState = ref(props.isSelecting ?? false);
const pressTimerRef = ref<ReturnType<typeof setTimeout> | null>(null);

const isSelecting = computed(() => props.isSelecting ?? isSelectingState.value);

const isStringSlot = computed(() => {
  // If there's only one default slot child and it's a string
  const slot = useSlots().default?.();
  return slot?.length === 1 && typeof slot[0].children === 'string';
});

const handleOnLongPress = () => {
  isSelectingState.value = true;

  emit('press');
};

const startPressTimer = () => {
  pressTimerRef.value = setTimeout(() => {
    handleOnLongPress();
  }, props.pressDuration ?? DEFAULT_PRESS_DETECT_DURATION);
};

const clearPressTimer = () => {
  if (pressTimerRef.value) {
    clearTimeout(pressTimerRef.value);
    pressTimerRef.value = null;
  }
};

const handleMouseDown = () => {
  clearPressTimer();
  startPressTimer();
};

const handleMouseUp = () => {
  isHovered.value = false;
  clearPressTimer();
};

const handleClickOutside = (event: MouseEvent) => {
  if (
    containerRef.value &&
    !containerRef.value.contains(event.target as Node)
  ) {
    isSelectingState.value = false;
    props.onClickOutside?.();
  }
};

const handleClick = (e: MouseEvent) => {
  if (isSelecting.value) {
    e.preventDefault();
    e.stopPropagation();
  }
};

const handleBlur = () => {
  isSelectingState.value = false;
};

onMounted(() => {
  document.addEventListener('mousedown', handleClickOutside);
});

onBeforeUnmount(() => {
  document.removeEventListener('mousedown', handleClickOutside);
  clearPressTimer();
});
</script>

<template>
  <span
    ref="containerRef"
    role="button"
    tabindex="0"
    @click="handleClick"
    @mousedown="handleMouseDown"
    @mouseup="handleMouseUp"
    @mouseleave="handleMouseUp"
    @touchstart="handleMouseDown"
    @touchend="handleMouseUp"
    @touchcancel="handleMouseUp"
    @blur="handleBlur"
    @mouseenter="isHovered = true"
    :style="{
      display: isStringSlot ? 'inline' : 'inline-block',
      cursor: 'pointer',
      userSelect: 'none',
      borderRadius: '0.375rem',
      outlineWidth: '2px',
      outlineOffset: '4px',
      outlineStyle: 'solid',
      outlineColor: isSelecting || isHovered ? 'inherit' : 'transparent',
      transition: 'all 100ms 50ms ease-in-out',
    }"
  >
    <slot />
  </span>
</template>
