// packages/lit-intlayer/src/html/types.ts
import type { HTMLTagsType } from '@intlayer/core/transpiler';
import type { TemplateResult } from 'lit';

/**
 * Helper to extract specific props from the configuration value.
 */
type PropsFromConfig<Value> = Value extends true
  ? {}
  : Value extends object
    ? Value
    : {};

/**
 * Common props for HTML elements rendered in Lit.
 * Components receive these as a plain object.
 */
type ElementProps = Record<string, unknown> & {
  children?: any;
};

/**
 * Lit component type — a function that takes props and returns a Lit template or string.
 */
export type LitHTMLComponent<P = {}> = (
  props: P & ElementProps
) => TemplateResult | string | any;

/**
 * Helper: Defines the mapping for the explicitly listed keys in T.
 */
type DefinedComponents<T, IsRequired extends boolean> = IsRequired extends true
  ? {
      [K in keyof T]: LitHTMLComponent<PropsFromConfig<T[K]>>;
    }
  : {
      [K in keyof T]?: LitHTMLComponent<PropsFromConfig<T[K]>>;
    };

/**
 * Helper: Defines the standard HTML tags NOT listed in T.
 */
type RestHTMLComponents<T> = {
  [K in Exclude<keyof HTMLTagsType, keyof T>]?: LitHTMLComponent;
};

/**
 * The supported modes for the HTMLComponents type.
 */
export type HTMLComponentMode =
  | 'permissive' // T is optional, HTML is optional, unknown strings allowed
  | 'optional' // T is optional, HTML is optional (Default)
  | 'inclusive' // T is required, HTML is optional
  | 'strict'; // T is required, HTML is forbidden

/**
 * Component map for HTML rendering in Lit.
 * Each component receives props and children and returns an HTML string.
 */
export type HTMLComponents<
  Mode extends HTMLComponentMode = 'optional',
  T = {},
> = Mode extends 'strict'
  ? DefinedComponents<T, true>
  : Mode extends 'inclusive'
    ? DefinedComponents<T, true> & RestHTMLComponents<T>
    : Mode extends 'permissive'
      ? DefinedComponents<T, false> &
          RestHTMLComponents<T> & {
            [key: string]: LitHTMLComponent;
          }
      : DefinedComponents<T, false> & RestHTMLComponents<T>;

// packages/solid-intlayer/src/html/types.ts
import type { HTMLTagsType } from '@intlayer/core/transpiler';
import type { JSX } from 'solid-js';

/**
 * Helper to extract specific props from the configuration value.
 */
type PropsFromConfig<Value> = Value extends true
  ? {}
  : Value extends object
    ? Value
    : {};

/**
 * Common props for all elements
 */
type ElementProps = JSX.HTMLAttributes<HTMLElement>;

/**
 * Solid Component type
 */
type SolidComponentType<P = {}> = (props: P) => JSX.Element;

/**
 * Helper: Defines the mapping for the explicitly listed keys in T.
 * Handles whether they are Required or Optional.
 */
type DefinedComponents<T, IsRequired extends boolean> = IsRequired extends true
  ? {
      // Required Case
      [K in keyof T]: SolidComponentType<ElementProps & PropsFromConfig<T[K]>>;
    }
  : {
      // Optional Case
      [K in keyof T]?: SolidComponentType<ElementProps & PropsFromConfig<T[K]>>;
    };

/**
 * Helper: Defines the standard HTML tags NOT listed in T.
 * These are always optional when included.
 */
type RestHTMLComponents<T> = {
  [K in Exclude<
    keyof HTMLTagsType,
    keyof T
  >]?: SolidComponentType<ElementProps>;
};

/**
 * The supported modes for the HTMLComponents type.
 */
export type HTMLComponentMode =
  | 'permissive' // T is optional, HTML is optional, unknown strings allowed
  | 'optional' // T is optional, HTML is optional (Default)
  | 'inclusive' // T is required, HTML is optional
  | 'strict'; // T is required, HTML is forbidden

/**
 * The main component definition with Mode support.
 */
export type HTMLComponents<
  Mode extends HTMLComponentMode = 'optional',
  T = {},
> = Mode extends 'strict'
  ? // Strict: Only keys in T are allowed, and they are required.
    DefinedComponents<T, true>
  : Mode extends 'inclusive'
    ? // Inclusive: Keys in T are required. Rest of HTML is optional.
      DefinedComponents<T, true> & RestHTMLComponents<T>
    : Mode extends 'permissive'
      ? // Permissive: Keys in T optional. Rest of HTML optional. Any other string allowed.
        DefinedComponents<T, false> &
          RestHTMLComponents<T> & {
            [key: string]: SolidComponentType<ElementProps>;
          }
      : // Optional (Default): Keys in T optional. Rest of HTML optional.
        DefinedComponents<T, false> & RestHTMLComponents<T>;
