// packages/solid-intlayer/src/editor/contexts/DictionariesRecordContext.tsx
'use client';

import type { Dictionary } from '@intlayer/core';
import { MessageKey } from '@intlayer/editor';
import {
  createContext,
  createMemo,
  useContext,
  type Component,
  type ParentProps,
  type Setter,
} from 'solid-js';
import { useCrossFrameState } from './useCrossFrameState';

export type DictionaryContent = Record<Dictionary['key'], Dictionary>;

type DictionariesRecordStatesContextType = {
  localeDictionaries: DictionaryContent;
};
type DictionariesRecordActionsContextType = {
  setLocaleDictionaries: Setter<DictionaryContent>;
  setLocaleDictionary: (dictionary: Dictionary) => void;
};

const DictionariesRecordStatesContext = createContext<
  DictionariesRecordStatesContextType | undefined
>(undefined);
const DictionariesRecordActionsContext = createContext<
  DictionariesRecordActionsContextType | undefined
>(undefined);

export const DictionariesRecordProvider: Component<ParentProps> = (props) => {
  const [localeDictionaries, setLocaleDictionaries] =
    useCrossFrameState<DictionaryContent>(
      MessageKey.INTLAYER_LOCALE_DICTIONARIES_CHANGED,
      undefined
    );

  const stateValue = createMemo(() => ({
    localeDictionaries: localeDictionaries() ?? {},
  }));

  const actionValue = createMemo(() => ({
    setLocaleDictionaries: setLocaleDictionaries as Setter<DictionaryContent>,
    setLocaleDictionary: (dictionary: Dictionary) => {
      setLocaleDictionaries((dictionaries) => ({
        ...dictionaries,
        [dictionary.key]: dictionary,
      }));
    },
  }));

  return (
    <DictionariesRecordStatesContext.Provider value={stateValue()}>
      <DictionariesRecordActionsContext.Provider value={actionValue()}>
        {props.children}
      </DictionariesRecordActionsContext.Provider>
    </DictionariesRecordStatesContext.Provider>
  );
};

export const useDictionariesRecordActions = () =>
  useContext(DictionariesRecordActionsContext);

export const useDictionariesRecord = () => {
  const actionsContext = useDictionariesRecordActions();
  const statesContext = useContext(DictionariesRecordStatesContext);

  if (!statesContext) {
    throw new Error(
      'useDictionariesRecordStates must be used within a DictionariesRecordProvider'
    );
  }

  return { ...statesContext, ...actionsContext };
};

// packages/@intlayer/editor-react/src/DictionariesRecordContext.tsx
'use client';

import type { Dictionary } from '@intlayer/core';
import { MessageKey } from '@intlayer/editor';
import {
  createContext,
  useContext,
  useMemo,
  type Dispatch,
  type FC,
  type PropsWithChildren,
  type SetStateAction,
} from 'react';
import { useCrossFrameState } from './useCrossFrameState';

export type DictionaryContent = Record<Dictionary['key'], Dictionary>;

type DictionariesRecordStatesContextType = {
  localeDictionaries: DictionaryContent;
};
type DictionariesRecordActionsContextType = {
  setLocaleDictionaries: Dispatch<SetStateAction<DictionaryContent>>;
  setLocaleDictionary: (dictionary: Dictionary) => void;
};

const DictionariesRecordStatesContext = createContext<
  DictionariesRecordStatesContextType | undefined
>(undefined);
const DictionariesRecordActionsContext = createContext<
  DictionariesRecordActionsContextType | undefined
>(undefined);

export const DictionariesRecordProvider: FC<PropsWithChildren> = ({
  children,
}) => {
  const [localeDictionaries, setLocaleDictionaries] =
    useCrossFrameState<DictionaryContent>(
      MessageKey.INTLAYER_LOCALE_DICTIONARIES_CHANGED,
      undefined
    );

  const stateValue = useMemo(
    () => ({
      localeDictionaries: localeDictionaries ?? {},
    }),
    [localeDictionaries]
  );

  const actionValue = useMemo(
    () => ({
      setLocaleDictionaries,
      setLocaleDictionary: (dictionary: Dictionary) => {
        setLocaleDictionaries((dictionaries) => ({
          ...dictionaries,
          [dictionary.key]: dictionary,
        }));
      },
    }),
    [setLocaleDictionaries]
  );

  return (
    <DictionariesRecordStatesContext.Provider value={stateValue}>
      <DictionariesRecordActionsContext.Provider value={actionValue}>
        {children}
      </DictionariesRecordActionsContext.Provider>
    </DictionariesRecordStatesContext.Provider>
  );
};

export const useDictionariesRecordActions = () =>
  useContext(DictionariesRecordActionsContext);

export const useDictionariesRecord = () => {
  const actionsContext = useDictionariesRecordActions();
  const statesContext = useContext(DictionariesRecordStatesContext);

  if (!statesContext) {
    throw new Error(
      'useDictionariesRecordStates must be used within a DictionariesRecordProvider'
    );
  }

  return { ...statesContext, ...actionsContext };
};
