// packages/react-intlayer/src/editor/useEditor.tsx
'use client';

import type { EditorStateManager } from '@intlayer/editor';
import { isEnabled } from '@intlayer/editor/isEnabled';
import type { Locale } from '@intlayer/types/allLocales';
import { useContext, useEffect, useRef } from 'react';
import { IntlayerClientContext } from '../client/IntlayerProvider';

/**
 * Initializes the Intlayer editor client singleton when the editor is enabled.
 * Syncs the current locale from the Intlayer context into the editor manager so
 * the editor always knows which locale the app is displaying.
 */
export const useEditor = () => {
  const { locale } = useContext(IntlayerClientContext) ?? {};
  const managerRef = useRef<EditorStateManager | null>(null);

  useEffect(() => {
    if (process.env['INTLAYER_EDITOR_ENABLED'] === 'false' || !isEnabled)
      return;

    import('@intlayer/editor').then(({ initEditorClient }) => {
      const manager = initEditorClient();
      managerRef.current = manager;

      if (locale) manager.currentLocale.set(locale as Locale);
    });

    return () => {
      managerRef.current = null;
      import('@intlayer/editor').then(({ stopEditorClient }) => {
        stopEditorClient();
      });
    };
  }, []);

  useEffect(() => {
    if (!locale || !managerRef.current) return;

    managerRef.current.currentLocale.set(locale as Locale);
  }, [locale]);
};

// packages/angular-intlayer/src/editor/useEditor.ts
import {
  DestroyRef,
  effect,
  Injector,
  inject,
  runInInjectionContext,
} from '@angular/core';
import { isEnabled } from '@intlayer/editor/isEnabled';
import type { Locale } from '@intlayer/types/allLocales';
import { INTLAYER_TOKEN, type IntlayerProvider } from '../client';

export const useEditor = () => {
  if (process.env.INTLAYER_EDITOR_ENABLED === 'false' || !isEnabled) return;

  const destroyRef = inject(DestroyRef, { optional: true });
  const client = inject<IntlayerProvider>(INTLAYER_TOKEN, {
    optional: true,
  } as any);
  const injector = inject(Injector);

  import('@intlayer/editor').then(({ initEditorClient }) => {
    const manager = initEditorClient();

    if (client) {
      const effectRef = runInInjectionContext(injector, () =>
        effect(() => {
          const locale = client.locale();
          if (locale) manager.currentLocale.set(locale as Locale);
        })
      );
      destroyRef?.onDestroy(() => effectRef.destroy());
    }
  });

  destroyRef?.onDestroy(() => {
    import('@intlayer/editor').then(({ stopEditorClient }) => {
      stopEditorClient();
    });
  });
};
