// packages/solid-intlayer/src/editor/contexts/useIframeClickInterceptor.tsx
'use client';

import { MessageKey, mergeIframeClick } from '@intlayer/editor';
import { onCleanup, onMount } from 'solid-js';
import { useCrossFrameMessageListener } from './useCrossFrameMessageListener';

/**
 * Custom hook that intercepts clicks on the page and sends them via `postMessage`.
 *
 * This is useful in iframe contexts where you want the parent frame to know
 * about click events happening within the iframe.
 */
export const useIframeClickInterceptor = () => {
  const postClickEvent = useCrossFrameMessageListener<undefined>(
    MessageKey.INTLAYER_IFRAME_CLICKED
  );

  onMount(() => {
    const handleClick = (event: MouseEvent) => {
      // Send click event to the parent frame
      postClickEvent();
    };

    // Add click event listener to the document
    document.addEventListener('mousedown', handleClick);

    // Cleanup function to remove the event listener
    onCleanup(() => {
      document.removeEventListener('mousedown', handleClick);
    });
  });
};

export const useIframeClickMerger = () =>
  useCrossFrameMessageListener<MessageEvent>(
    MessageKey.INTLAYER_IFRAME_CLICKED,
    mergeIframeClick
  );

// packages/angular-intlayer/src/editor/useIframeClickInterceptor.ts
import { DestroyRef, inject } from '@angular/core';
import { MessageKey, mergeIframeClick } from '@intlayer/editor';
import { createSharedComposable } from './createSharedComposable';
import { useCrossFrameMessageListener } from './useCrossFrameMessageListener';

/* ─────────────────────────────────────────────
   1.  "Interceptor" – send a postMessage when
       the editor iframe itself is clicked.
────────────────────────────────────────────── */
/**
 * Hook that intercepts clicks in the iframe and sends them to the parent window
 * This allows the parent window to know when the iframe is clicked
 */
export const useIframeClickInterceptor = createSharedComposable(() => {
  const postMessage = useCrossFrameMessageListener<undefined>(
    MessageKey.INTLAYER_IFRAME_CLICKED
  );

  const handler = () => {
    postMessage();
  };

  // Use Angular's DestroyRef for cleanup instead of Vue's lifecycle hooks
  try {
    const destroyRef = inject(DestroyRef, { optional: true });

    if (destroyRef && typeof window !== 'undefined') {
      // Set up event listener immediately
      window.addEventListener('mousedown', handler);

      // Clean up on destroy
      destroyRef.onDestroy(() =>
        window.removeEventListener('mousedown', handler)
      );
    }
  } catch {
    console.warn(
      'useIframeClickInterceptor called outside injection context; ' +
        'event listener setup may not be available.'
    );
  }
});

/**
 * Hook for the parent window to listen for iframe clicks and merge them
 * This makes iframe clicks behave as if they happened in the parent window
 */
export const useIframeClickMerger = createSharedComposable(() => {
  useIframeClickInterceptor();

  useCrossFrameMessageListener<MessageEvent>(
    MessageKey.INTLAYER_IFRAME_CLICKED,
    mergeIframeClick
  );
});
