// packages/react-intlayer/src/markdown/MarkdownProvider.tsx
'use client';

import {
  createContext,
  type FC,
  type HTMLAttributes,
  type PropsWithChildren,
  type ReactNode,
  useContext,
} from 'react';
import type { HTMLComponents } from '../html/HTMLComponentTypes';
import { compiler, type MarkdownRendererOptions } from './processor';

export type MarkdownProviderOptions = {
  /** Forces the compiler to always output content with a block-level wrapper. */
  forceBlock?: boolean;
  /** Forces the compiler to always output content with an inline wrapper. */
  forceInline?: boolean;
  /** Whether to preserve frontmatter in the markdown content. */
  preserveFrontmatter?: boolean;
  /** Whether to use the GitHub Tag Filter for security. */
  tagfilter?: boolean;
};

type MarkdownContextValue = {
  components?: HTMLComponents<'permissive', {}>;
  renderMarkdown: (
    markdown: string,
    options?: MarkdownProviderOptions,
    components?: HTMLComponents<'permissive', {}>,
    wrapper?: FC<HTMLAttributes<HTMLElement>>
  ) => ReactNode | Promise<ReactNode>;
};

type MarkdownProviderProps = PropsWithChildren<
  MarkdownProviderOptions & {
    components?: HTMLComponents<'permissive', {}>;
    wrapper?: FC<HTMLAttributes<HTMLElement>>;
    renderMarkdown?: (
      markdown: string,
      options?: MarkdownProviderOptions,
      components?: HTMLComponents<'permissive', {}>,
      wrapper?: FC<HTMLAttributes<HTMLElement>>
    ) => ReactNode | Promise<ReactNode>;
  }
>;

const MarkdownContext = createContext<MarkdownContextValue | undefined>(
  undefined
);

export const useMarkdownContext = () => useContext(MarkdownContext);

const mergeOptions = (
  baseOptions: MarkdownRendererOptions,
  options: MarkdownProviderOptions = {},
  components: HTMLComponents<'permissive', {}> = {},
  wrapper?: FC<HTMLAttributes<HTMLElement>>
): MarkdownRendererOptions => {
  return {
    ...baseOptions,
    ...options,
    forceBlock: options.forceBlock ?? baseOptions.forceBlock,
    forceInline: options.forceInline ?? baseOptions.forceInline,
    preserveFrontmatter:
      options.preserveFrontmatter ?? baseOptions.preserveFrontmatter,
    tagfilter: options.tagfilter ?? baseOptions.tagfilter,
    wrapper: wrapper || baseOptions.wrapper,

    forceWrapper: !!(wrapper || baseOptions.wrapper),
    components: { ...baseOptions.components, ...components },
  };
};

/**
 * Provider for the MarkdownRenderer component.
 *
 * It will provide the `renderMarkdown` function to the context, which can be used to render markdown.
 *
 * ```tsx
 * const content = useIntlayer('app');
 *
 * return (
 *   <div>
 *     {content.markdown} // Will be rendered with the components and options provided to the MarkdownProvider
 *   </div>
 * );
 * ```
 *
 * @example
 * ```tsx
 * <MarkdownProvider components={{ h1: CustomHeading }}>
 *   <MarkdownRenderer>
 *     {markdownContent}
 *   </MarkdownRenderer>
 * </MarkdownProvider>
 * ```
 */
export const MarkdownProvider: FC<MarkdownProviderProps> = ({
  children,
  components,
  wrapper,
  forceBlock,
  forceInline,
  preserveFrontmatter,
  tagfilter,
  renderMarkdown: customRenderFn,
}) => {
  const baseOptions: MarkdownRendererOptions = {
    components,
    forceBlock,
    forceInline,
    wrapper,
    forceWrapper: !!wrapper,
    preserveFrontmatter,
    tagfilter,
  };

  // Standard internal renderer
  const defaultRenderMarkdown = (
    markdown: string,
    options?: MarkdownProviderOptions,
    components?: HTMLComponents<'permissive', {}>,
    wrapper?: FC<HTMLAttributes<HTMLElement>>
  ) => {
    const mergedOptions = mergeOptions(
      baseOptions,
      options,
      components,
      wrapper
    );

    return compiler(markdown, mergedOptions);
  };

  // Wrapper for user-provided custom renderer
  // Note: We wrap in a clean Provider to prevent infinite recursion
  const customRenderMarkdownWrapper = (
    markdown: string,
    options?: MarkdownProviderOptions,
    components?: HTMLComponents<'permissive', {}>,
    wrapper?: FC<HTMLAttributes<HTMLElement>>
  ) => (
    <MarkdownContext.Provider value={undefined}>
      {customRenderFn?.(markdown, options, components, wrapper)}
    </MarkdownContext.Provider>
  );

  return (
    <MarkdownContext.Provider
      value={{
        components,
        renderMarkdown: customRenderFn
          ? customRenderMarkdownWrapper
          : defaultRenderMarkdown,
      }}
    >
      {children}
    </MarkdownContext.Provider>
  );
};

// packages/solid-intlayer/src/markdown/MarkdownProvider.tsx
import {
  type Component,
  createContext,
  type JSXElement,
  type ParentProps,
  useContext,
} from 'solid-js';
import type { HTMLComponents } from '../html/types';
import { compileMarkdown } from './compiler';

export type MarkdownProviderOptions = {
  /** Forces the compiler to always output content with a block-level wrapper. */
  forceBlock?: boolean;
  /** Whether to preserve frontmatter in the markdown content. */
  preserveFrontmatter?: boolean;
  /** Whether to use the GitHub Tag Filter. */
  tagfilter?: boolean;
};

type RenderMarkdownOptions = MarkdownProviderOptions & {
  components?: HTMLComponents<'permissive', {}>;
  wrapper?: any;
};

type MarkdownProviderValue = {
  components?: HTMLComponents<'permissive', {}>;
  renderMarkdown: (
    content: string,
    options?: MarkdownProviderOptions,
    components?: HTMLComponents<'permissive', {}>,
    wrapper?: any
  ) => JSXElement;
};

export const MarkdownContext = createContext<MarkdownProviderValue>();

export type MarkdownProviderProps = ParentProps<{
  components?: HTMLComponents<'permissive', {}>;
  wrapper?: any;
  forceBlock?: boolean;
  preserveFrontmatter?: boolean;
  tagfilter?: boolean;
  renderMarkdown?: (
    content: string,
    options?: MarkdownProviderOptions,
    components?: HTMLComponents<'permissive', {}>,
    wrapper?: any
  ) => JSXElement;
}>;

export const MarkdownProvider: Component<MarkdownProviderProps> = (props) => {
  const defaultRenderMarkdown = (
    content: string,
    options?: MarkdownProviderOptions,
    componentsOverride?: HTMLComponents<'permissive', {}>,
    wrapperOverride?: any
  ): JSXElement => {
    if (props.renderMarkdown) {
      return props.renderMarkdown(
        content,
        options,
        componentsOverride,
        wrapperOverride
      );
    }

    const mergedOptions: RenderMarkdownOptions = {
      forceBlock: options?.forceBlock ?? props.forceBlock,
      preserveFrontmatter:
        options?.preserveFrontmatter ?? props.preserveFrontmatter,
      tagfilter: options?.tagfilter ?? props.tagfilter,
      wrapper: wrapperOverride || props.wrapper,
      forceWrapper: !!(wrapperOverride || props.wrapper),
      components: {
        ...props.components,
        ...(componentsOverride ?? {}),
      },
    };

    return compileMarkdown(content, mergedOptions);
  };

  return (
    <MarkdownContext.Provider
      value={{
        components: props.components,
        renderMarkdown: defaultRenderMarkdown,
      }}
    >
      {props.children}
    </MarkdownContext.Provider>
  );
};

export const useMarkdown = () => {
  const context = useContext(MarkdownContext);

  if (!context) {
    throw new Error(
      'useMarkdown must be used within a MarkdownProvider. To fix this error, wrap your component with <MarkdownProvider>.'
    );
  }

  return context;
};
