// examples/vite-react-app/src/App.tsx
import type { FC, ReactNode } from 'react';
import { useIntlayer } from 'react-intlayer';
import {
  useCompact,
  useCurrency,
  useDate,
  useList,
  useNumber,
  usePercentage,
  useRelativeTime,
  useUnit,
} from 'react-intlayer/format';
import { HTMLProvider } from 'react-intlayer/html';
import { MarkdownProvider } from 'react-intlayer/markdown';
import './App.css';
import viteLogo from '/vite.svg';
import reactLogo from './assets/react.svg';
import { LocaleSwitcher } from './components/LangSwitcherDropDown';
import { QualifiedContentDemo } from './components/QualifiedContentDemo';
import { LocaleRouter } from './Router';

const PoTestSection: FC = () => {
  const content = useIntlayer('index');
  return (
    <div
      style={{
        padding: '20px',
        border: '2px solid #646cff',
        borderRadius: '12px',
        marginTop: '30px',
        background: 'rgba(100, 108, 255, 0.05)',
        textAlign: 'left',
      }}
    >
      <h2 style={{ color: '#646cff', marginTop: 0 }}>PO File Content Test</h2>
      <div
        style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '10px' }}
      >
        <strong>Default Key:</strong> <span>{content.test_key}</span>
        <strong>Default Welcome:</strong> <span>{content.welcome_message}</span>
      </div>
    </div>
  );
};

// ─── Benchmark table ─────────────────────────────────────────────────────────

const th: React.CSSProperties = {
  padding: '8px 14px',
  textAlign: 'left',
  fontWeight: 600,
  background: 'rgba(100,108,255,0.18)',
  borderBottom: '2px solid rgba(100,108,255,0.4)',
  whiteSpace: 'nowrap',
};
const td: React.CSSProperties = {
  padding: '6px 14px',
  borderBottom: '1px solid rgba(255,255,255,0.07)',
  verticalAlign: 'top',
};
const code: React.CSSProperties = {
  background: 'rgba(100,108,255,0.12)',
  padding: '2px 7px',
  borderRadius: 4,
  fontSize: '0.85em',
  fontFamily: 'monospace',
};
const sectionHdr: React.CSSProperties = {
  padding: '6px 14px',
  background: 'rgba(100,108,255,0.08)',
  fontWeight: 700,
  fontSize: '0.78em',
  letterSpacing: '0.08em',
  textTransform: 'uppercase',
  color: '#888',
};

type Row = { name: string; desc: string; result: ReactNode };

const BenchmarkTable: FC = () => {
  const content = useIntlayer('benchmark');
  const number = useNumber();
  const percentage = usePercentage();
  const currency = useCurrency();
  const date = useDate();
  const relativeTime = useRelativeTime();
  const unit = useUnit();
  const compact = useCompact();
  const list = useList();

  const now = new Date();
  const in3Days = new Date(now.getTime() + 3 * 864e5);

  const preview = (node: ReactNode) => (
    <div style={{ fontSize: '0.82em', lineHeight: 1.4 }}>{node}</div>
  );

  const sections: { label: string; rows: Row[] }[] = [
    {
      label: 'Content Nodes',
      rows: [
        { name: 't()', desc: 'Simple translation', result: content.n01_t },
        {
          name: 'enu() −2',
          desc: "count=-2 → '<-1'",
          result: content.n02_enu(-2),
        },
        {
          name: 'enu() 0',
          desc: "count=0 → '0'",
          result: content.n02_enu(0),
        },
        {
          name: 'enu() 1',
          desc: "count=1 → '1'",
          result: content.n02_enu(1),
        },
        {
          name: 'enu() 7',
          desc: "count=7 → '>5'",
          result: content.n02_enu(7),
        },
        {
          name: 'enu() 25',
          desc: "count=25 → '>19'",
          result: content.n02_enu(25),
        },
        {
          name: 'cond() true',
          desc: 'condition=true',
          result: content.n03_cond(true),
        },
        {
          name: 'cond() false',
          desc: 'condition=false',
          result: content.n03_cond(false),
        },
        {
          name: 'gender() male',
          desc: "gender='male'",
          result: content.n04_gender('male'),
        },
        {
          name: 'gender() female',
          desc: "gender='female'",
          result: content.n04_gender('female'),
        },
        {
          name: "select() 'published'",
          desc: "publishType='published'",
          result: content.n27_select('published'),
        },
        {
          name: "select() 'archived'",
          desc: "publishType='archived' → fallback",
          result: content.n27_select('archived'),
        },
        {
          name: 'select() + insert()',
          desc: "publishType='draft' · {name:'Alice'}",
          result: content.n28_select_insert_t('draft')({ name: 'Alice' }),
        },
        {
          name: 'insert()',
          desc: "insert('Hello {{name}}…') · {name:'Alice',age:30}",
          result: content.n05_insert({ name: 'Alice', age: 30 }),
        },
        {
          name: 'md()',
          desc: 'Markdown string',
          result: preview(content.n06_md),
        },
        {
          name: 'html()',
          desc: 'HTML string',
          result: content.n07_html.use({}),
        },
        {
          name: 'plural() 1',
          desc: "count=1 → 'one'",
          result: content.n22_plural(1),
        },
        {
          name: 'plural() 5',
          desc: "count=5 → 'other'",
          result: content.n22_plural(5),
        },
      ],
    },
    {
      label: 'Combinations',
      rows: [
        {
          name: 'insert(t())',
          desc: '{name:"Alice", place:"Paris"}',
          result: content.n08_insert_t({ name: 'Alice', place: 'Paris' }),
        },
        {
          name: 't(md())',
          desc: 'Translation of markdown',
          result: preview(content.n09_t_of_md),
        },
        {
          name: 'md(t())',
          desc: 'Markdown from translation',
          result: preview(content.n10_md_t),
        },
        {
          name: 'enu(t()) 2',
          desc: 'Enumeration of t(), count=2',
          result: content.n11_enu_t(2),
        },
        {
          name: 'insert(enu(t()))',
          desc: '{count:3,name:"Alice"}(3)',
          result: content.n12_insert_enu_t({ count: 3, name: 'Alice' })(3),
        },
        {
          name: 'cond(t()) true',
          desc: 'Condition of t(), true',
          result: content.n13_cond_t(true),
        },
        {
          name: 'cond(insert(t()))',
          desc: 'true · {name:"Alice"}',
          result: content.n14_cond_insert_t(true)?.({ name: 'Alice' }),
        },
        {
          name: 'gender(insert(t()))',
          desc: "female · {name:'Alice'}",
          result: content.n15_gender_insert_t('female')?.({ name: 'Alice' }),
        },
        {
          name: 'plural(html()) 1',
          desc: "count=1 → '<b>1</b> day'",
          result: content.n23_plural_html(1),
        },
        {
          name: 'plural(html()) 5',
          desc: "count=5 → '<b>5</b> days'",
          result: content.n23_plural_html(5),
        },
        {
          name: 'insert(html())',
          desc: "{name:'Alice'} → 'Hello <b>Alice</b>'",
          result: content.n24_insert_html({ name: 'Alice' }),
        },
        {
          name: 'plural(md()) 1',
          desc: "count=1 → '**1** day'",
          result: preview(content.n25_plural_md(1)),
        },
        {
          name: 'plural(md()) 5',
          desc: "count=5 → '**5** days'",
          result: preview(content.n25_plural_md(5)),
        },
        {
          name: 'insert(md())',
          desc: "{name:'Alice'} → 'Hello **Alice**'",
          result: preview(content.n26_insert_md({ name: 'Alice' })),
        },
      ],
    },
    {
      label: 'Data Structures',
      rows: [
        {
          name: 'nested object',
          desc: 'obj.level1.level2',
          result: content.n17_nested_object.level1.level2,
        },
        {
          name: "array ['string']",
          desc: "['item1','item2','item3']",
          result: content.n18_array_strings,
        },
        {
          name: 'array [t()]',
          desc: 'Array of translations',
          result: content.n19_array_translations,
        },
        {
          name: 'array [{obj}]',
          desc: 'Array of {name,role}',
          result: content.n20_array_objects
            .map((o) => `${o.name.value} (${o.role.value})`)
            .join(' · '),
        },
        {
          name: "nest('app','title')",
          desc: 'Cross-dict reference',
          result: content.n21_nest,
        },
      ],
    },
    {
      label: 'Formatters',
      rows: [
        { name: 'useNumber()', desc: '123456.789', result: number(123456.789) },
        { name: 'usePercentage()', desc: '0.25', result: percentage(0.25) },
        {
          name: 'useCurrency()',
          desc: '1234.5, EUR',
          result: currency(1234.5, { currency: 'EUR' }),
        },
        { name: 'useDate()', desc: 'now, short', result: date(now, 'short') },
        {
          name: 'useRelativeTime()',
          desc: 'now → +3 days',
          result: relativeTime(now, in3Days, { unit: 'day' }),
        },
        {
          name: 'useUnit()',
          desc: '5, kilometer, long',
          result: unit(5, { unit: 'kilometer', unitDisplay: 'long' }),
        },
        { name: 'useCompact()', desc: '1200', result: compact(1200) },
        {
          name: 'useList()',
          desc: "['apple','banana','orange']",
          result: list(['apple', 'banana', 'orange']),
        },
      ],
    },
  ];

  let rowIndex = 0;

  return (
    <div style={{ margin: '24px 0', overflowX: 'auto' }}>
      <h2 style={{ marginBottom: 16, fontSize: '1.25em', color: '#646cff' }}>
        Intlayer Node Benchmark
      </h2>
      <table
        style={{
          width: '100%',
          borderCollapse: 'collapse',
          fontSize: '0.88em',
          textAlign: 'left',
        }}
      >
        <thead>
          <tr>
            <th style={{ ...th, width: 36 }}>#</th>
            <th style={{ ...th, width: 200 }}>Name</th>
            <th style={{ ...th, width: 280 }}>Description</th>
            <th style={th}>Result</th>
          </tr>
        </thead>
        <tbody>
          {sections.map((section) => (
            <>
              <tr key={section.label}>
                <td colSpan={4} style={sectionHdr}>
                  {section.label}
                </td>
              </tr>
              {section.rows.map((row) => {
                rowIndex++;
                const i = rowIndex;
                return (
                  <tr
                    key={i}
                    style={{
                      background:
                        i % 2 === 0 ? 'rgba(255,255,255,0.025)' : 'transparent',
                    }}
                  >
                    <td
                      style={{ ...td, color: '#666', fontFamily: 'monospace' }}
                    >
                      {i}
                    </td>
                    <td style={td}>
                      <code style={code}>{row.name}</code>
                    </td>
                    <td
                      style={{
                        ...td,
                        color: '#aaa',
                        fontFamily: 'monospace',
                        fontSize: '0.83em',
                      }}
                    >
                      {row.desc}
                    </td>
                    <td style={td}>{row.result}</td>
                  </tr>
                );
              })}
            </>
          ))}
        </tbody>
      </table>
    </div>
  );
};

// ─── App ─────────────────────────────────────────────────────────────────────

const AppContent: FC = () => {
  const content = useIntlayer('app');
  const mdContent = useIntlayer('my-markdown-content');

  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank" rel="noopener">
          <img
            src={viteLogo}
            className="logo"
            alt={content.viteLogoLabel.value}
          />
        </a>
        <a href="https://react.dev" target="_blank" rel="noopener">
          <img
            src={reactLogo}
            className="logo react"
            alt={content.reactLogoLabel.value}
          />
        </a>
      </div>

      <h1>{content.title}</h1>

      {mdContent}

      <BenchmarkTable />

      <QualifiedContentDemo />

      <PoTestSection />

      <p className="read-the-docs">{content.readTheDocs}</p>

      <div className="absolute right-5 bottom-5 z-50">
        <LocaleSwitcher />
      </div>
    </>
  );
};

const App: FC = () => (
  <LocaleRouter>
    <MarkdownProvider
      components={{
        h1: (props) => (
          <h1 style={{ color: '#646cff' }} {...props}>
            {props.children}
          </h1>
        ),
        ComponentDemo: (props) => (
          <div
            style={{
              padding: '10px',
              background: 'rgba(100, 108, 255, 0.1)',
              borderRadius: '8px',
              border: '1px solid #646cff',
            }}
            {...props}
          >
            MDX Component Demo
          </div>
        ),
      }}
    >
      <HTMLProvider
        components={{
          CustomComponent: (props) => (
            <h1 style={{ color: 'blue' }} {...props}>
              Custom 2
            </h1>
          ),
        }}
      >
        <AppContent />
      </HTMLProvider>
    </MarkdownProvider>
  </LocaleRouter>
);

export default App;

// examples/vite-svelte-app/src/App.svelte
<script lang="ts">
import { useIntlayer } from 'svelte-intlayer';
import {
  useCompact,
  useCurrency,
  useDate,
  useList,
  useNumber,
  usePercentage,
  useRelativeTime,
  useUnit,
} from 'svelte-intlayer/format';
import { MarkdownProvider } from 'svelte-intlayer/markdown';
import svelteLogo from './assets/svelte.svg';
import QualifiedContentDemo from './components/QualifiedContentDemo/index.svelte';
import LocaleSwitcher from './lib/LocaleSwitcher.svelte';

let count = $state(0);
const app = useIntlayer('app');
const bm = useIntlayer('benchmark');

const number = useNumber();
const percentage = usePercentage();
const currency = useCurrency();
const date = useDate();
const relativeTime = useRelativeTime();
const unit = useUnit();
const compact = useCompact();
const list = useList();

const now = new Date();
const in3Days = new Date(now.getTime() + 3 * 864e5);

type Row = { id: number; name: string; desc: string; result: unknown };
type Section = { label: string; rows: Row[] };

const getSections = (): Section[] => {
  let id = 0;
  const r = (name: string, desc: string, result: unknown): Row => ({
    id: ++id,
    name,
    desc,
    result,
  });
  return [
    {
      label: 'Content Nodes',
      rows: [
        r('t()', 'Simple translation', $bm.n01_t),
        r('enu() −2', "count=-2 → '<-1'", $bm.n02_enu(-2)),
        r('enu() 0', "count=0 → '0'", $bm.n02_enu(0)),
        r('enu() 1', "count=1 → '1'", $bm.n02_enu(1)),
        r('enu() 7', "count=7 → '>5'", $bm.n02_enu(7)),
        r('enu() 25', "count=25 → '>19'", $bm.n02_enu(25)),
        r('cond() true', 'condition=true', $bm.n03_cond(true)),
        r('cond() false', 'condition=false', $bm.n03_cond(false)),
        r("gender() 'male'", "gender='male'", $bm.n04_gender('male')),
        r("gender() 'female'", "gender='female'", $bm.n04_gender('female')),
        r(
          'insert()',
          "{name:'Alice', age:30}",
          $bm.n05_insert({ name: 'Alice', age: 30 })
        ),
        r('md()', 'Markdown string', 'md' as const),
        r('html()', 'HTML string', 'html' as const),
        r('plural() 1', "count=1 → 'one'", $bm.n22_plural(1)),
        r('plural() 5', "count=5 → 'other'", $bm.n22_plural(5)),
      ],
    },
    {
      label: 'Combinations',
      rows: [
        r(
          'insert(t())',
          "{name:'Alice', place:'Paris'}",
          $bm.n08_insert_t({ name: 'Alice', place: 'Paris' })
        ),
        r('t(md())', 'Translation of markdown', 'n09_t_of_md' as const),
        r('md(t())', 'Markdown from translation', 'n10_md_t' as const),
        r('enu(t()) 2', 'count=2', $bm.n11_enu_t(2)),
        r(
          'insert(enu(t()))',
          '{count:3,name:"Alice"}(3)',
          $bm.n12_insert_enu_t({ count: 3, name: 'Alice' })(3)
        ),
        r('cond(t()) true', 'true', $bm.n13_cond_t(true)),
        r(
          'cond(insert(t()))',
          "true · {name:'Alice'}",
          $bm.n14_cond_insert_t(true)?.({ name: 'Alice' })
        ),
        r(
          'gender(insert(t()))',
          "female · {name:'Alice'}",
          $bm.n15_gender_insert_t('female')?.({ name: 'Alice' })
        ),
        r(
          'plural(html()) 1',
          "count=1 → '<b>1</b> day'",
          'n23_plural_html_1' as const
        ),
        r(
          'plural(html()) 5',
          "count=5 → '<b>5</b> days'",
          'n23_plural_html_5' as const
        ),
        r(
          'insert(html())',
          "{name:'Alice'} → 'Hello <b>Alice</b>'",
          'n24_insert_html' as const
        ),
        r(
          'plural(md()) 1',
          "count=1 → '**1** day'",
          'n25_plural_md_1' as const
        ),
        r(
          'plural(md()) 5',
          "count=5 → '**5** days'",
          'n25_plural_md_5' as const
        ),
        r(
          'insert(md())',
          "{name:'Alice'} → 'Hello **Alice**'",
          'n26_insert_md' as const
        ),
      ],
    },
    {
      label: 'Data Structures',
      rows: [
        r(
          'nested object',
          'obj.level1.level2',
          $bm.n17_nested_object.level1.level2
        ),
        r(
          "array ['string']",
          "['item1','item2','item3']",
          ($bm.n18_array_strings as string[]).join(', ')
        ),
        r('array [t()]', 'Array of translations', $bm.n19_array_translations),
        r(
          'array [{obj}]',
          'Array of {name,role}',
          $bm.n20_array_objects.map((o) => `${o.name} (${o.role})`).join(' · ')
        ),
        r("nest('app','title')", 'Cross-dict reference', $bm.n21_nest),
      ],
    },
    {
      label: 'Formatters',
      rows: [
        r('useNumber()', '123456.789', $number(123456.789)),
        r('usePercentage()', '0.25', $percentage(0.25)),
        r(
          'useCurrency()',
          '1234.5, EUR',
          $currency(1234.5, { currency: 'EUR' })
        ),
        r('useDate()', 'now, short', $date(now, 'short')),
        r(
          'useRelativeTime()',
          'now → +3 days',
          $relativeTime(now, in3Days, { unit: 'day' })
        ),
        r(
          'useUnit()',
          '5, kilometer, long',
          $unit(5, { unit: 'kilometer', unitDisplay: 'long' })
        ),
        r('useCompact()', '1200', $compact(1200)),
        r(
          'useList()',
          "['apple','banana','orange']",
          $list(['apple', 'banana', 'orange'])
        ),
      ],
    },
  ];
};

let sections = $derived(getSections());
</script>

<MarkdownProvider>
  <main>
    <div class="locale-switcher-container">
      <LocaleSwitcher />
    </div>

    <div>
      <a href="https://vitejs.dev" target="_blank" rel="noopener">
        <img src="/vite.svg" class="logo" alt={$app.viteLogoLabel} />
      </a>
      <a href="https://svelte.dev" target="_blank" rel="noopener">
        <img src={svelteLogo} class="logo svelte" alt={$app.svelteLogoLabel} />
      </a>
    </div>

    <h1>{$app.title}</h1>

    <div class="card">
      <button onclick={() => count++}>
        {$app.countIs({ count })}
      </button>
    </div>

    <div class="benchmark-wrap">
      <h2 class="benchmark-title">Intlayer Node Benchmark</h2>
      <div class="table-scroll">
        <table class="benchmark-table">
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Description</th>
              <th>Result</th>
            </tr>
          </thead>
          <tbody>
            {#each sections as section}
              <tr class="section-header">
                <td colspan="4">{section.label}</td>
              </tr>
              {#each section.rows as row}
                <tr class:even={row.id % 2 === 0}>
                  <td class="col-id">{row.id}</td>
                  <td class="col-name"><code>{row.name}</code></td>
                  <td class="col-desc">{row.desc}</td>
                  <td class="col-result">
                    {#if row.result === 'md'}
                      {@const Comp = $bm.n06_md}
                      <div class="md-preview"><Comp /></div>
                    {:else if row.result === 'html'}
                      {@html String($bm.n07_html)}
                    {:else if row.result === 'n09_t_of_md'}
                      {@const Comp = $bm.n09_t_of_md}
                      <div class="md-preview"><Comp /></div>
                    {:else if row.result === 'n10_md_t'}
                      {@const Comp = $bm.n10_md_t}
                      <div class="md-preview"><Comp /></div>
                    {:else if row.result === 'n23_plural_html_1'}
                      {@html String($bm.n23_plural_html(1))}
                    {:else if row.result === 'n23_plural_html_5'}
                      {@html String($bm.n23_plural_html(5))}
                    {:else if row.result === 'n24_insert_html'}
                      {@html String($bm.n24_insert_html({ name: 'Alice' }))}
                    {:else if row.result === 'n25_plural_md_1'}
                      {@const Comp = $bm.n25_plural_md(1)}
                      <div class="md-preview"><Comp /></div>
                    {:else if row.result === 'n25_plural_md_5'}
                      {@const Comp = $bm.n25_plural_md(5)}
                      <div class="md-preview"><Comp /></div>
                    {:else if row.result === 'n26_insert_md'}
                      {@const Comp = $bm.n26_insert_md({ name: 'Alice' })}
                      <div class="md-preview"><Comp /></div>
                    {:else}
                      {row.result}
                    {/if}
                  </td>
                </tr>
              {/each}
            {/each}
          </tbody>
        </table>
      </div>
    </div>

    <QualifiedContentDemo />

    <p class="read-the-docs">{$app.readTheDocs}</p>
  </main>
</MarkdownProvider>

<style>
  main {
    max-width: 1100px;
    margin: 0 auto;
    padding: 2rem;
    text-align: center;
    position: relative;
  }
  .locale-switcher-container {
    position: absolute;
    top: 1em;
    right: 1em;
  }
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover { filter: drop-shadow(0 0 2em #646cffaa); }
  .logo.svelte:hover { filter: drop-shadow(0 0 2em #ff3e00aa); }

  .benchmark-wrap { margin: 1.5rem 0; text-align: left; }
  .benchmark-title { font-size: 1.25rem; color: #ff3e00; margin-bottom: 1rem; }
  .table-scroll { overflow-x: auto; }

  .benchmark-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.88em;
  }
  .benchmark-table th {
    padding: 8px 14px;
    background: rgba(255, 62, 0, 0.15);
    border-bottom: 2px solid rgba(255, 62, 0, 0.4);
    text-align: left;
    font-weight: 600;
    white-space: nowrap;
  }
  .benchmark-table td {
    padding: 6px 14px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.07);
    vertical-align: top;
  }
  .benchmark-table tr.even td { background: rgba(255, 255, 255, 0.025); }

  .section-header td {
    padding: 6px 14px;
    background: rgba(255, 62, 0, 0.07);
    font-weight: 700;
    font-size: 0.75em;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    color: #888;
  }

  .col-id { width: 36px; color: #666; font-family: monospace; }
  .col-name { width: 200px; }
  .col-name code {
    background: rgba(255, 62, 0, 0.12);
    padding: 2px 7px;
    border-radius: 4px;
    font-size: 0.85em;
  }
  .col-desc { width: 280px; color: #aaa; font-family: monospace; font-size: 0.83em; }
  .col-result { max-width: 360px; }
  .md-preview { font-size: 0.82em; line-height: 1.4; }

  .read-the-docs { color: #888; margin-top: 2rem; }
  .card { margin: 1rem 0; }
</style>
