// examples/tanstack-start-solid-app/src/routes/__root.tsx
import {
  createRootRouteWithContext,
  getRouteApi,
  HeadContent,
  Outlet,
  Scripts,
} from '@tanstack/solid-router';
import { TanStackRouterDevtools } from '@tanstack/solid-router-devtools';
import { defaultLocale, getHTMLTextDir } from 'intlayer';
import { IntlayerProvider } from 'solid-intlayer';
import { Suspense } from 'solid-js';
import { HydrationScript } from 'solid-js/web';
import Header from '../components/Header';
import styleCss from '../styles.css?url';

const localeRoute = getRouteApi('/{-$locale}');

export const Route = createRootRouteWithContext()({
  head: () => ({
    links: [{ rel: 'stylesheet', href: styleCss }],
  }),
  shellComponent: RootComponent,
});

function RootComponent() {
  const params = localeRoute.useParams();
  const locale = params().locale ?? defaultLocale;

  return (
    <html dir={getHTMLTextDir(locale)} lang={locale}>
      <head>
        <HydrationScript />
      </head>
      <body>
        <HeadContent />
        <IntlayerProvider locale={locale}>
          <Suspense>
            <Header />
            <Outlet />
            <TanStackRouterDevtools />
          </Suspense>
        </IntlayerProvider>
        <Scripts />
      </body>
    </html>
  );
}

// examples/tanstack-start-app/src/routes/__root.tsx
import {
  createRootRouteWithContext,
  getRouteApi,
  HeadContent,
  Scripts,
} from '@tanstack/react-router';
import { defaultLocale, getHTMLTextDir } from 'intlayer';
import type { ReactNode } from 'react';
import { IntlayerProvider } from 'react-intlayer';

import Header from '#/components/Header';
import { LocaleSwitcher } from '#/components/locale-switcher';

import appCss from '../styles.css?url';

const localeRoute = getRouteApi('/{-$locale}');

export const Route = createRootRouteWithContext<{}>()({
  head: () => ({
    links: [
      {
        href: appCss,
        rel: 'stylesheet',
      },
    ],
    meta: [
      {
        charSet: 'utf-8',
      },
      {
        content: 'width=device-width, initial-scale=1',
        name: 'viewport',
      },
      {
        title: 'TanStack Start Starter',
      },
    ],
  }),

  shellComponent: RootDocument,
});

function RootDocument({ children }: { children: ReactNode }) {
  const params = localeRoute.useParams();
  const locale = params?.locale ?? defaultLocale;

  return (
    <html dir={getHTMLTextDir(locale)} lang={locale}>
      <head>
        <HeadContent />
      </head>
      <body>
        <IntlayerProvider locale={locale}>
          <Header />
          <LocaleSwitcher />
          {children}
        </IntlayerProvider>
        <Scripts />
      </body>
    </html>
  );
}
