// compat/react-intl/src/useDictionaryDynamic.ts
'use client';

import type { Dictionary } from '@intlayer/types/dictionary';
import type {
  DictionaryKeys,
  LocalesValues,
  StrictModeLocaleMap,
} from '@intlayer/types/module_augmentation';
import { useMemo } from 'react';
import {
  useDictionaryDynamic as useDictionaryDynamicBase,
  useLocale,
} from 'react-intlayer';
import { createIntlObject } from './createIntlObject';
import type { DictionaryIntlShape } from './dictionaryIntlShape';
import { createDictionaryLookup } from './useDictionary';

/**
 * Dynamic dictionary-accepting variant of `useIntl`.
 *
 * Counterpart to {@link useDictionary} for dictionaries imported lazily per
 * locale. Used internally by the build-time optimization.
 */
export const useDictionaryDynamic = <
  const T extends Dictionary,
  const K extends DictionaryKeys,
>(
  dictionaryPromise: StrictModeLocaleMap<() => Promise<T>>,
  key: K
): DictionaryIntlShape<K> => {
  const content = useDictionaryDynamicBase<T, K>(dictionaryPromise, key);
  const { locale } = useLocale();

  return useMemo(
    () =>
      createIntlObject(
        locale as LocalesValues,
        createDictionaryLookup(key, content)
      ) as DictionaryIntlShape<K>,
    [locale, key, content]
  );
};

// packages/angular-intlayer/src/client/useDictionaryDynamic.ts
'use client';

import { computed, inject } from '@angular/core';
import { internationalization } from '@intlayer/config/built';
import type { Dictionary } from '@intlayer/types/dictionary';
import type {
  DictionaryKeys,
  LocalesValues,
  StrictModeLocaleMap,
} from '@intlayer/types/module_augmentation';
import { INTLAYER_TOKEN, type IntlayerProvider } from './installIntlayer';
import { useDictionary } from './useDictionary';
import { useLoadDynamic } from './useLoadDynamic';

/**
 * On the server side, Hook that transform a dictionary and return the content
 *
 * If the locale is not provided, it will use the locale from the client context
 */
export const useDictionaryDynamic = <
  const T extends Dictionary,
  const K extends DictionaryKeys,
>(
  dictionaryPromise: StrictModeLocaleMap<() => Promise<T>>,
  key: K,
  locale?: LocalesValues
) => {
  const intlayer = inject<IntlayerProvider>(INTLAYER_TOKEN);

  const localeTarget = computed(
    () => locale ?? intlayer?.locale() ?? internationalization.defaultLocale
  );

  const dictionary = useLoadDynamic<T>(
    `${String(key)}.${localeTarget()}`,
    (dictionaryPromise as any)[localeTarget()]?.()
  ) as T;

  return useDictionary(dictionary, localeTarget() as any);
};
