// packages/react-intlayer/src/client/useDictionary.ts
'use client';

import {
  getDictionarySelectorCacheKey,
  resolveDictionaryArgument,
} from '@intlayer/core/dictionaryManipulator';
import type {
  Dictionary,
  DictionarySelectorForGroup,
  QualifiedDictionaryGroup,
} from '@intlayer/types/dictionary';
import type {
  DeclaredLocales,
  LocalesValues,
} from '@intlayer/types/module_augmentation';
import { useContext, useMemo } from 'react';
import { getDictionary } from '../getDictionary';
import { IntlayerClientContext } from './IntlayerProvider';

/**
 * Client-side hook that transforms a dictionary (or qualified dictionary
 * group) and returns the content.
 *
 * If the locale is not provided (directly or through the selector), it will
 * use the locale from the client context. The same applies to the variant,
 * which falls back to the provider's ambient `variant`.
 */
export const useDictionary = <
  const T extends Dictionary | QualifiedDictionaryGroup,
  const A extends
    | LocalesValues
    | DictionarySelectorForGroup<T> = DeclaredLocales,
>(
  dictionary: T,
  localeOrSelector?: A
) => {
  const { locale: currentLocale, variant: contextVariant } =
    useContext(IntlayerClientContext) ?? {};

  // Layers the provider's locale and variant under the call-site argument.
  // This is the seam the build-time optimize transform lands on: it rewrites
  // `useIntlayer('key', selector)` into `useDictionary(dict, selector)`, so an
  // ambient variant has to be applied here to survive the rewrite.
  const argument =
    process.env.INTLAYER_DICTIONARY_SELECTOR !== 'false'
      ? resolveDictionaryArgument({
          localeOrSelector,
          contextLocale: currentLocale,
          contextVariant,
          dictionaryKey: dictionary.key,
        })
      : (localeOrSelector ?? currentLocale);

  // Stable identity of the resolved argument for memoization — a provider
  // variant is often a fresh object literal on every render, so the dependency
  // has to be its serialization, never its reference.
  const argumentIdentity =
    typeof argument === 'object' && argument !== null
      ? `${argument.locale ?? ''}|${getDictionarySelectorCacheKey(argument)}`
      : argument;

  return useMemo(
    () => getDictionary<T, A>(dictionary, argument as A),
    [dictionary.key, argumentIdentity]
  );
};

// packages/angular-intlayer/src/client/useDictionary.ts
import { computed, inject, type Signal } from '@angular/core';
import { resolveDictionaryArgument } from '@intlayer/core/dictionaryManipulator';
import type {
  Dictionary,
  DictionarySelectorForGroup,
  QualifiedDictionaryGroup,
  ResolveQualifiedDictionaryContent,
} from '@intlayer/types/dictionary';
import type {
  DeclaredLocales,
  ExtractSelectorLocale,
  LocalesValues,
} from '@intlayer/types/module_augmentation';
import { getDictionary } from '../getDictionary';
import type { DeepTransformContent } from '../plugins';
import { INTLAYER_TOKEN, type IntlayerProvider } from './installIntlayer';

/**
 * Angular hook that transforms a dictionary (or qualified dictionary group)
 * and returns its reactive content for the given locale or selector.
 */
export const useDictionary = <
  const T extends Dictionary | QualifiedDictionaryGroup,
  const A extends
    | LocalesValues
    | DictionarySelectorForGroup<T> = DeclaredLocales,
>(
  dictionary: T,
  localeOrSelector?: A
): Signal<
  DeepTransformContent<
    ResolveQualifiedDictionaryContent<T, A>,
    ExtractSelectorLocale<A>
  >
> => {
  const intlayer = inject<IntlayerProvider>(INTLAYER_TOKEN);

  /** a *stable* reactive dictionary object */
  const content = computed(() => {
    const currentLocale = intlayer?.locale();

    if (process.env.INTLAYER_DICTIONARY_SELECTOR !== 'false') {
      // Layers the provider's locale and variant under the call-site argument.
      // This is also the seam the build-time optimize transform lands on, which
      // rewrites `useIntlayer('key', selector)` into `useDictionary(dict, …)`.
      return getDictionary(
        dictionary,
        resolveDictionaryArgument({
          localeOrSelector,
          contextLocale: currentLocale,
          contextVariant: intlayer?.variant?.(),
          dictionaryKey: dictionary.key,
        }) as A
      ) as any;
    }

    return getDictionary(
      dictionary,
      (localeOrSelector ?? currentLocale) as A
    ) as any;
  });

  return content; // all consumers keep full reactivity
};
