// packages/solid-intlayer/src/client/useDictionary.ts
import type {
  DeclaredLocales,
  Dictionary,
  LocalesValues,
} from '@intlayer/types';
import { createMemo, useContext } from 'solid-js';
import { getDictionary } from '../getDictionary';
import { IntlayerClientContext } from './IntlayerProvider';

/**
 * On the client side, Hook that transform a dictionary and return the content
 *
 * If the locale is not provided, it will use the locale from the client context
 */
export const useDictionary = <
  T extends Dictionary,
  L extends LocalesValues = DeclaredLocales,
>(
  dictionary: T,
  locale?: L
) => {
  const context = useContext(IntlayerClientContext);

  return createMemo(() => {
    const localeTarget = locale ?? context?.locale?.();

    return getDictionary<T, L>(dictionary, localeTarget as L);
  });
};

// packages/react-intlayer/src/client/useDictionary.ts
'use client';

import type { Dictionary } from '@intlayer/types/dictionary';
import type {
  DeclaredLocales,
  LocalesValues,
} from '@intlayer/types/module_augmentation';
import { useContext, useMemo } from 'react';
import { getDictionary } from '../getDictionary';
import { IntlayerClientContext } from './IntlayerProvider';

/**
 * On the server side, Hook that transform a dictionary and return the content
 *
 * If the locale is not provided, it will use the locale from the client context
 */
export const useDictionary = <
  T extends Dictionary,
  L extends LocalesValues = DeclaredLocales,
>(
  dictionary: T,
  locale?: L
) => {
  const { locale: currentLocale } = useContext(IntlayerClientContext) ?? {};

  return useMemo(() => {
    const localeTarget = locale ?? currentLocale;

    return getDictionary<T, L>(dictionary, localeTarget as L);
  }, [dictionary.key, currentLocale, locale]);
};
