// packages/react-intlayer/src/client/useIntlayerAsync.ts
'use client';

import type { LocalesValues } from '@intlayer/config/client';
import {
  type DictionaryKeys,
  getIntlayer,
  getIntlayerAsync,
} from '@intlayer/core';
import { useContext, useEffect, useMemo, useState } from 'react';
import { IntlayerClientContext } from './IntlayerProvider';

/**
 * On the client side, Hook that picking one dictionary by its key and return the content
 *
 * This hook will prerender the locale dictionary and fetch simultaneously the distant dictionaries to hydrate it.
 *
 *
 * If the locale is not provided, it will use the locale from the client context
 */
export const useIntlayerAsync = <T extends DictionaryKeys>(
  key: T,
  locale?: LocalesValues
) => {
  const { locale: currentLocale } = useContext(IntlayerClientContext);
  const localeTarget = locale ?? currentLocale;
  const localeDictionary = getIntlayer(key, localeTarget);
  const [distantDictionary, setDistantDictionary] = useState<
    typeof localeDictionary | null | undefined
  >(undefined);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    setIsLoading(true);

    getIntlayerAsync(key)
      .then((distantDictionary) => {
        if (distantDictionary) {
          setDistantDictionary(distantDictionary);
        }
      })
      .finally(() => {
        setIsLoading(false);
      });
  }, []);

  const dictionary = useMemo(
    () => distantDictionary ?? localeDictionary,
    [distantDictionary, localeDictionary]
  );

  return { ...(dictionary as object), isLoading } as typeof localeDictionary & {
    isLoading: boolean;
  };
};

// packages/solid-intlayer/src/client/useIntlayerAsync.ts
import type { LocalesValues } from '@intlayer/config/client';
import {
  type DictionaryKeys,
  getIntlayer,
  getIntlayerAsync,
} from '@intlayer/core';
import { createMemo, createSignal, onMount, useContext } from 'solid-js';
import { IntlayerClientContext } from './IntlayerProvider';

/**
 * SolidJS composable that picks one dictionary by its key and returns the content.
 *
 * 1. Uses the local (bundled) dictionary for the initial render.
 * 2. Hydrates with the distant dictionary once it resolves.
 *
 * If `locale` is not provided, it falls back to the locale found in the
 * `IntlayerClientContext`.
 */
export const useIntlayerAsync = <T extends DictionaryKeys>(
  key: T,
  locale?: LocalesValues
) => {
  const { locale: currentLocale } = useContext(IntlayerClientContext);
  const localeTarget = locale ?? currentLocale();

  // Local (eager) dictionary
  const localeDictionary = getIntlayer(key, localeTarget);

  // Reactive state
  const [distantDictionary, setDistantDictionary] = createSignal<
    typeof localeDictionary | null
  >(null);
  const [isLoading, setIsLoading] = createSignal(false);

  // Fetch the remote dictionary after mount
  onMount(() => {
    setIsLoading(true);
    getIntlayerAsync(key)
      .then((dict) => dict && setDistantDictionary(dict))
      .finally(() => setIsLoading(false));
  });

  // Choose distant dictionary when it exists
  const dictionary = createMemo(() => distantDictionary() ?? localeDictionary);

  /*
   * Spread the current dictionary value so callers can destructure
   * keys just like in other framework versions, and add the reactive
   * `isLoading` flag.
   */
  return {
    ...dictionary(),
    isLoading: isLoading(),
  } as typeof localeDictionary & { isLoading: boolean };
};
