// packages/react-intlayer/src/client/format/useCompact.ts
'use client';

import { compact } from '@intlayer/core/formatters';
import { useCallback, useContext } from 'react';
import { IntlayerClientContext } from '../IntlayerProvider';

/**
 * React client hook that provides a compact number formatter
 * bound to the current application locale.
 *
 * @example
 * ```tsx
 * const formatCompact = useCompact();
 * formatCompact(1500); // "1.5K"
 * ```
 */
export const useCompact = () => {
  const { locale } = useContext(IntlayerClientContext) ?? {};

  return useCallback(
    (...args: Parameters<typeof compact>) =>
      compact(args[0], {
        ...args[1],
        locale: args[1]?.locale ?? locale,
      }),
    [locale]
  );
};

// packages/angular-intlayer/src/format/useCompact.ts
import { computed, inject } from '@angular/core';
import { compact } from '@intlayer/core/formatters';
import { IntlayerProvider } from '../client/installIntlayer';

export const useCompact = () => {
  const intlayer = inject(IntlayerProvider);

  return computed(
    () =>
      (...args: Parameters<typeof compact>) =>
        compact(args[0], {
          ...args[1],
          locale: args[1]?.locale ?? intlayer.locale(),
        })
  );
};
