// packages/lit-intlayer/src/format/useDate.ts
import { date, presets } from '@intlayer/core/formatters';
import type { ReactiveController, ReactiveControllerHost } from 'lit';
import { getIntlayerClient } from '../client/installIntlayer';

/**
 * ReactiveController that provides a locale-bound date formatter.
 */
class DateController implements ReactiveController {
  private readonly host: ReactiveControllerHost;
  private _unsubscribe: (() => void) | null = null;
  value: (...args: Parameters<typeof date>) => string;

  constructor(host: ReactiveControllerHost) {
    this.host = host;
    const client = getIntlayerClient();
    this.value = (...args) => {
      const options =
        typeof args[1] === 'string'
          ? { ...presets[args[1]], locale: client.locale }
          : { ...args[1], locale: args[1]?.locale ?? client.locale };
      return date(args[0], options as Parameters<typeof date>[1]);
    };

    host.addController(this);
  }

  hostConnected(): void {
    const client = getIntlayerClient();
    this._unsubscribe = client.subscribe((newLocale) => {
      this.value = (...args) => {
        const options =
          typeof args[1] === 'string'
            ? { ...presets[args[1]], locale: newLocale }
            : { ...args[1], locale: args[1]?.locale ?? newLocale };
        return date(args[0], options as Parameters<typeof date>[1]);
      };
      this.host.requestUpdate();
    });
  }

  hostDisconnected(): void {
    this._unsubscribe?.();
    this._unsubscribe = null;
  }
}

/**
 * Reactive hook that provides a locale-bound date formatter.
 */
export const useDate = (host: ReactiveControllerHost): DateController =>
  new DateController(host);

// packages/angular-intlayer/src/format/useDate.ts
import { computed, inject } from '@angular/core';
import { date, presets } from '@intlayer/core/formatters';
import { INTLAYER_TOKEN } from '../client/installIntlayer';

/**
 * Angular client hook that provides a localized date/time formatter.
 */
export const useDate = () => {
  const intlayer = inject(INTLAYER_TOKEN);

  return computed(() => (...args: Parameters<typeof date>) => {
    const locale = intlayer.locale();
    const options =
      typeof args[1] === 'string'
        ? { ...presets[args[1]], locale }
        : { ...args[1], locale: args[1]?.locale ?? locale };

    return date(args[0], options as Parameters<typeof date>[1]);
  });
};
