// packages/solid-intlayer/src/format/useRelativeTime.ts
import { relativeTime } from '@intlayer/core/formatters';
import { useContext } from 'solid-js';
import { IntlayerClientContext } from '../client/IntlayerProvider';

/**
 * Solid client hook that provides a localized relative time formatter.
 */
export const useRelativeTime = () => {
  const { locale } = useContext(IntlayerClientContext) ?? {};

  return (...args: Parameters<typeof relativeTime>) =>
    relativeTime(args[0], args[1], {
      ...args[2],
      locale: args[2]?.locale ?? locale(),
    });
};

// packages/angular-intlayer/src/format/useRelativeTime.ts
import { computed, inject } from '@angular/core';
import { relativeTime } from '@intlayer/core/formatters';
import { IntlayerProvider } from '../client/installIntlayer';

export const useRelativeTime = () => {
  const intlayer = inject(IntlayerProvider);

  return computed(
    () =>
      (...args: Parameters<typeof relativeTime>) =>
        relativeTime(args[0], args[1], {
          ...args[2],
          locale: args[2]?.locale ?? intlayer.locale(),
        })
  );
};
