// examples/nuxt-4-app/pages/about.vue
<script setup lang="ts">
import { useIntlayer } from 'vue-intlayer';

// useHead is auto-imported in Nuxt, but you can import it explicitly if needed
// import { useHead } from '#imports';

const content = useIntlayer('about-page');

useHead({
  title: content.metaTitle.raw, // Use .raw for primitive string access
  meta: [
    {
      name: 'description',
      content: content.metaDescription.raw, // Use .raw for primitive string access
    },
  ],
});
</script>
  
<template>
  <h1><content.title /></h1>
</template>

// examples/solid-start-app/src/routes/[[locale]]/about.tsx
import { Meta, Title } from '@solidjs/meta';
import { useIntlayer } from 'solid-intlayer';

export default function About() {
  const content = useIntlayer('about-page');

  return (
    <main>
      <Title>{content.metaTitle.value}</Title>
      <Meta content={content.metaDescription.value} name="description" />
      <h1>{content.title}</h1>
      <p>{content.description}</p>
    </main>
  );
}
