// examples/vite-svelte-app/src/lib/LocaleSwitcher.svelte
<script lang="ts">
import { getLocaleName } from 'intlayer';
import { useLocale } from 'svelte-intlayer';

// Get locale information and setLocale function
const { locale, availableLocales, setLocale } = useLocale();

// Handle locale change
const changeLocale = (event: Event) => {
  const target = event.target as HTMLSelectElement;
  const newLocale = target.value;
  setLocale(newLocale);
};
</script>

<div class="locale-switcher">
  <select value={$locale} on:change={changeLocale}>
    {#each availableLocales ?? [] as loc}
      <option value={loc}>
        {getLocaleName(loc)}
      </option>
    {/each}
  </select>
</div>

<style>
  .locale-switcher {
    display: inline-block;
  }

  select {
    padding: 0.5em 1em;
    border: 1px solid #646cff;
    border-radius: 8px;
    background-color: #1a1a1a;
    color: rgba(255, 255, 255, 0.87);
    font-family: inherit;
    font-size: 1em;
    cursor: pointer;
    transition: border-color 0.25s;
  }

  select:hover {
    border-color: #747bff;
  }

  select:focus {
    outline: 4px auto -webkit-focus-ring-color;
  }
</style>

// examples/vite-vue-app/src/components/LocaleSwitcher.vue
<template>
  <div class="locale-switcher">
    <select v-model="selectedLocale" @change="changeLocale">
      <option v-for="loc in availableLocales" :key="loc" :value="loc">
        {{ getLocaleName(loc) }}
      </option>
    </select>
  </div>
</template>

<script setup>
import { ref, watch } from 'vue';
import { getLocaleName } from 'intlayer';
import { useLocale } from 'vue-intlayer';

// Get locale information and setLocale function
const { locale, availableLocales, setLocale } = useLocale();

// Track the selected locale with a ref
const selectedLocale = ref(locale.value);

// Update the locale when the selection changes
const changeLocale = () => {
  setLocale(selectedLocale.value);
};

// Keep the selectedLocale in sync with the global locale
watch(
  () => locale.value,
  (newLocale) => {
    selectedLocale.value = newLocale;
  }
);
</script>

<style scoped>
.locale-switcher {
  margin: 1rem 0;
}
select {
  padding: 0.5rem;
  border-radius: 4px;
  font-size: 1rem;
}
</style>
