// packages/angular-intlayer/src/format/useCurrency.ts
import { computed, inject } from '@angular/core';
import { currency } from '@intlayer/core/formatters';
import { IntlayerProvider } from '../client/installIntlayer';

export const useCurrency = () => {
  const intlayer = inject(IntlayerProvider);

  return computed(
    () =>
      (...args: Parameters<typeof currency>) =>
        currency(args[0], {
          ...args[1],
          locale: args[1]?.locale ?? intlayer.locale(),
        })
  );
};

// packages/solid-intlayer/src/format/useCurrency.ts
import { currency } from '@intlayer/core/formatters';
import { useContext } from 'solid-js';
import { IntlayerClientContext } from '../client/IntlayerProvider';

/**
 * Solid client hook that provides a localized currency formatter.
 */
export const useCurrency = () => {
  const { locale } = useContext(IntlayerClientContext) ?? {};

  return (...args: Parameters<typeof currency>) =>
    currency(args[0], {
      ...args[1],
      locale: args[1]?.locale ?? locale(),
    });
};
